/* V5.4 deterministic experimental battle sessions with presentation-ready events. */
(function (V4) {
  'use strict';
  const battle = V4.engines.battle = V4.engines.battle || {}, clamp=(v,min,max)=>Math.max(min,Math.min(max,v));
  const hash=value=>{let out=2166136261;for(const char of String(value)){out^=char.charCodeAt(0);out=Math.imul(out,16777619);}return out|0;};
  const fruitsOf=f=>[f.fruit,...(f.secondaryFruits||[])].filter(Boolean), elementsOf=f=>[...new Set(fruitsOf(f).flatMap(x=>x.elementTags||['fruit-energy']))];
  const actionCost={style:6,haki:9,weapon:8,fruit:14,recover:0,guard:4}; const scales={style:'standard',haki:'heavy',weapon:'standard',fruit:'heavy',recover:'light',guard:'light'};
  const makeState=f=>{const maxHp=Math.round(180+(f.physical?.durability||50)*1.8+(f.physical?.stamina||50)*.7),maxStamina=Math.round(80+(f.physical?.stamina||50)*.8);return {combatant:f,name:f.displayName||f.name||f.id,hp:maxHp,maxHp,stamina:maxStamina,maxStamina,stm:maxStamina,maxStm:maxStamina,guard:0,cooldowns:{},stats:{damage:0,dodges:0,guards:0,counters:0,hakiContacts:0,affinityAdvantages:0,largestHit:0}};};
  const canUse=(s,a)=>a==='style'||a==='recover'||s.stamina>=actionCost[a];
  const selectAction=(fighter,state,rng)=>{if(state.hp/state.maxHp<.26&&rng.chance(.28))return 'recover';if(state.stamina<16&&rng.chance(.25))return 'guard';const fruitFocus=/fruit|darkness|magma|freezer|goddess/.test(fighter.behaviorProfile||'');if(fruitsOf(fighter).length&&canUse(state,'fruit')&&rng.chance(fruitFocus?.68:.44))return'fruit';if(fighter.weapon&&canUse(state,'weapon')&&rng.chance(.42))return'weapon';if((fighter.haki?.arm||fighter.haki?.coc)&&canUse(state,'haki')&&rng.chance(.48))return'haki';return'style';};
  const actionElement=(fighter,action,rng)=>action==='fruit'?(rng.pick(elementsOf(fighter))||'fruit-energy'):action==='weapon'?(fighter.weapon?.family==='blade'?'blade':'physical'):action==='haki'?'haki':fighter.style?.type==='sword'?'blade':'physical';
  const procedural=(fighter,action,element)=>{const prefix={fruit:element==='fire'?'Flame':element==='gravity'?'Gravity':element==='darkness'?'Darkness':'Devil Fruit',weapon:'Weapon',haki:'Armament Art',style:fighter.style?.name||'Combat Art'}[action]||'Combat Art';const suffix={fruit:'Rising Breaker',weapon:'Crossing Strike',haki:'Iron Breaker',style:'Grand Line Crash'}[action]||'Strike';return `${prefix}: ${suffix}`;};
  const technique=(fighter,action,rng)=>{const records=(V4.database.battleActions||[]).filter(item=>item.ownerProfileIds?.includes(fighter.profile?.id)&&item.category===action&&(!fighter._battleCooldowns?.[item.id]));return records.length?rng.pick(records):{id:`expanded-${action}`,name:procedural(fighter,action,actionElement(fighter,action,rng)),category:action,scale:scales[action],staminaCost:actionCost[action],powerCoefficient:1,accuracyModifier:0,elementTags:[] ,cooldown:0,source:'expanded'};};
  battle.matchup=(attacker,defender,element)=>{let multiplier=1,bestAgainst=null;for(const defense of elementsOf(defender)){const current=V4.database.elementChart?.multiplier(element,defense)||1;if(Math.abs(current-1)>Math.abs(multiplier-1)){multiplier=current;bestAgainst=defense;}}if(element==='magma'&&elementsOf(defender).includes('fire')){multiplier=Math.max(multiplier,1.35);bestAgainst='fire';}if(element==='darkness'&&fruitsOf(defender).length){multiplier=Math.max(multiplier,1.25);bestAgainst='fruit-energy';}return{multiplier,bestAgainst};};
  const initiative=(f,s,rng)=>(f.physical?.speed||50)*.65+(f.mental?.battleIQ||50)*.15+(f.haki?.obs||0)*.25+s.stamina*.04+rng.roll(1,20);
  const event=(session,phase,data)=>session.events.push({turn:session.turn,phase,...data});
  const resolve=(session,a,d,action)=>{const attacker=a.combatant,defender=d.combatant,tech=technique(attacker,action,session.rng),element=tech.elementTags?.[0]||actionElement(attacker,action,session.rng),match=battle.matchup(attacker,defender,element),scale=tech.scale||scales[action];event(session,'decision',{attacker:a.name,defender:d.name,action,technique:tech.name,scale,element});event(session,'telegraph',{attacker:a.name,technique:tech.name,scale,element,message:`${a.name} prepares ${tech.name}.`});
    if(action==='recover'){const healed=Math.min(a.maxHp-a.hp,8+(attacker.physical?.recovery||40)*.18);a.hp+=healed;a.stamina=Math.min(a.maxStamina,a.stamina+16);session.log.push(`${a.name} creates distance and recovers ${Math.round(healed)} HP.`);event(session,'aftermath',{attacker:a.name,message:`RECOVERY +${Math.round(healed)} HP`,scale:'light'});return;}
    if(action==='guard'){a.guard=10+(attacker.haki?.arm||0)*.16;a.stamina=Math.max(0,a.stamina-actionCost.guard);a.stats.guards++;session.log.push(`${a.name} raises a Haki Guard.`);event(session,'resolution',{attacker:a.name,message:'GUARD READY',outcome:'guard',scale:'light'});return;}
    a.stamina=Math.max(0,a.stamina-(tech.staminaCost||actionCost[action])); const observation=(defender.haki?.obs||0)+(defender.haki?.hasAdvObs?17:0),speedGap=(attacker.physical?.speed||50)-(defender.physical?.speed||50),accuracy=clamp(.72+speedGap*.002+(attacker.haki?.obs||0)*.0015-observation*.001+(tech.accuracyModifier||0),.30,.96);event(session,'counter-window',{defender:d.name,message:`${d.name} reads the attack.`,scale});
    const dodgeChance=clamp(.035+(observation-(attacker.haki?.obs||0))*0.0015+((defender.physical?.speed||50)-(attacker.physical?.speed||50))*.0015-(scale==='finisher'?.02:0),.01,.28);if(session.rng.chance(dodgeChance)){d.stats.dodges++;session.log.push(`${d.name} DODGES ${a.name}'s ${tech.name}.`);event(session,'resolution',{attacker:a.name,defender:d.name,message:'DODGED',outcome:'dodged',scale});return;}
    if(!session.rng.chance(accuracy)){session.log.push(`${a.name}'s ${tech.name} misses.`);event(session,'resolution',{attacker:a.name,defender:d.name,message:'MISSED',outcome:'miss',scale});return;}
    const haki=(attacker.haki?.arm||0)*.28+(attacker.haki?.hasAdvArm?10:0)+(attacker.haki?.hasAdvCoc?18:0),fruit=fruitsOf(attacker).reduce((sum,x)=>sum+x.power,0)/Math.max(1,Math.sqrt(fruitsOf(attacker).length))*(attacker.fruitMastery||65)/100*(attacker.awakened?1.12:1),strength=attacker.physical?.strength||50,iq=attacker.mental?.battleIQ||50,base=action==='fruit'?fruit*.58+iq*.18:action==='weapon'?strength*.35+(attacker.weapon?.power||0)*.45+haki:action==='haki'?strength*.45+haki*1.15:strength*.38+(attacker.style?.power||45)*.34,defense=(defender.physical?.durability||50)*.32+(defender.haki?.arm||0)*.25+d.guard,contact=!(fruitsOf(defender).some(x=>x.type==='Logia')&&!attacker.haki?.arm&&!attacker.specialRules?.includes('darkness-nullification'));
    let damage=Math.max(4,(base-defense*.48+session.rng.roll(2,14))*match.multiplier*(tech.powerCoefficient||1)); if(!contact)damage*=.35; if(attacker.specialRules?.includes('localized-singularity')&&action==='fruit'){damage*=1.16;a.stamina=Math.max(0,a.stamina-9);}damage*=clamp(.72+a.stamina/a.maxStamina*.38,.68,1.1); if(d.guard>0){damage*=.62;d.stats.guards++;} const counterChance=clamp(.02+(observation-(attacker.haki?.obs||0))*.001+(defender.mental?.battleIQ||50)*.0007,0,.16);let counter=false;if(session.rng.chance(counterChance)&&d.hp>0){counter=true;d.stats.counters++;a.stamina=Math.max(0,a.stamina-7);damage*=.72;}
    d.hp=Math.max(0,d.hp-damage);a.stats.damage+=damage;a.stats.largestHit=Math.max(a.stats.largestHit,damage);if(contact&&fruitsOf(defender).some(x=>x.type==='Logia')&&attacker.haki?.arm)a.stats.hakiContacts++;const outcome=!contact?'LOGIA PHASE':counter?'COUNTERED':d.guard>0?'GUARDED':match.multiplier>1.05?'AFFINITY ADVANTAGE':match.multiplier<.95?'RESISTED':'HIT';if(match.multiplier>1.05)a.stats.affinityAdvantages++;session.log.push(`${a.name} uses ${tech.name} for ${Math.round(damage)} damage — ${outcome}.`);event(session,'impact',{attacker:a.name,defender:d.name,technique:tech.name,scale,element,damage:Math.round(damage),outcome});event(session,'resolution',{attacker:a.name,defender:d.name,message:outcome,outcome:outcome.toLowerCase().replace(/ /g,'-'),scale,contact,affinity:match});if(element==='darkness'&&fruitsOf(defender).length){session.summary.nullifications++;event(session,'aftermath',{message:'FRUIT NULLIFIED — darkness drags the user into contact.',scale:'heavy'});}if(match.multiplier>1.05){session.summary.elementAdvantages.push({attacker:a.name,element,defense:match.bestAgainst,multiplier:match.multiplier});event(session,'aftermath',{message:element==='magma'&&match.bestAgainst==='fire'?'MAGMA OVERWHELMS FLAME':`AFFINITY ADVANTAGE ×${match.multiplier.toFixed(2)}`,scale});} if(tech.cooldown){a.cooldowns[tech.id]=tech.cooldown;attacker._battleCooldowns={...(attacker._battleCooldowns||{}),[tech.id]:tech.cooldown};}
  };
  const finish=session=>{if(session.f1.hp<=0&&session.f2.hp<=0)session.winner=null;else if(session.f1.hp<=0)session.winner=session.f2;else if(session.f2.hp<=0)session.winner=session.f1;else if(session.turn>=30)session.winner=session.f1.hp/session.f1.maxHp===session.f2.hp/session.f2.maxHp?null:session.f1.hp/session.f1.maxHp>session.f2.hp/session.f2.maxHp?session.f1:session.f2;session.done=!!session.winner||session.turn>=30;if(session.done){session.log.push(session.winner?`${session.winner.name} wins the experimental simulation.`:'The battle ends without a decisive winner.');event(session,'aftermath',{message:session.winner?`${session.winner.name} WINS!`:'DRAW',scale:'finisher'});}};
  battle.createSession=(first,second,options={})=>{if(!first||!second)throw new Error('Two battle-ready fighters are required.');const seed=Number.isFinite(Number(options.seed))?Number(options.seed)|0:hash(`${first.id}:${second.id}:${options.arena||'training'}`),session={version:V4.build?.appVersion||'unknown',f1:makeState(first),f2:makeState(second),rng:V4.engines.rng.create(seed),turn:0,done:false,winner:null,log:[],events:[],actionHistory:[],summary:{seed,turns:0,elementAdvantages:[],nullifications:0},playerIndex:options.playerIndex??null,arena:options.arena||'training'};if(session.f1.combatant.haki?.hasCoc&&session.f2.combatant.haki?.hasCoc)session.log.push("Conqueror's Haki rolls across the arena as neither fighter gives ground.");return session;};
  battle.step=(session,playerAction)=>{if(session.done)return session;session.turn++;session.summary.turns=session.turn;session.log.push(`--- Turn ${session.turn} ---`);session.events=[];for(const s of [session.f1,session.f2]){s.guard=0;for(const key of Object.keys(s.cooldowns)){s.cooldowns[key]--;if(s.cooldowns[key]<=0)delete s.cooldowns[key];}s.combatant._battleCooldowns=s.cooldowns;}const firstActs=initiative(session.f1.combatant,session.f1,session.rng)>=initiative(session.f2.combatant,session.f2,session.rng),first=firstActs?session.f1:session.f2,second=firstActs?session.f2:session.f1,firstAction=first===session.f1&&session.playerIndex===0?playerAction:first===session.f2&&session.playerIndex===1?playerAction:selectAction(first.combatant,first,session.rng);resolve(session,first,second,firstAction);let secondAction=null;if(second.hp>0){secondAction=second===session.f1&&session.playerIndex===0?playerAction:second===session.f2&&session.playerIndex===1?playerAction:selectAction(second.combatant,second,session.rng);resolve(session,second,first,secondAction);}session.actionHistory.push({turn:session.turn,first:first.name,firstAction,second:second.name,secondAction,events:session.events.map(item=>({...item}))});for(const s of [session.f1,session.f2]){s.stamina=Math.min(s.maxStamina,s.stamina+5);s.stm=s.stamina;}finish(session);return session;};
  battle.replay=session=>({version:session.version,engine:'experimental-v5.4',seed:session.summary.seed,arena:session.arena,fighters:[session.f1.combatant.id,session.f2.combatant.id],actionHistory:session.actionHistory,summary:session.summary});
  battle.simulate=(first,second,options={})=>{const session=battle.createSession(first,second,options);while(!session.done)battle.step(session);return{...session,experimental:true};};
}(window.OnePieceRollV4));


