/* V5.5 coherent identity history. Additive only: no generated stat or power formula is changed here. */
(function(V4){'use strict';
  const life=V4.engines.lifeHistory=V4.engines.lifeHistory||{};
  const hash=(seed,salt)=>{let n=(Number(seed)||1)^salt; n=Math.imul(n^(n>>>16),2246822507);return(n^(n>>>13))>>>0;};
  const pick=(list,seed,salt)=>list[hash(seed,salt)%list.length];
  const region=id=>(V4.database.regions||[]).find(item=>item.id===id)||(V4.database.regions||[])[0];
  const ageProfile=(age,race)=>{const stage=age<13?'child':age<18?'teen':age<=28?'young-adult':age<=55?'adult':age<=75?'veteran':'elder';const active=Math.max(0,age-(age<18?12:16));return {age,activeYears:active,developmentalStage:stage,physicalPrimeModifier:age>=18&&age<=40?1:age<18?.86:age<=55?.96:.86,experienceOpportunity:Math.min(100,active*4),declineFactors:age>55?['Wear and old injuries may limit recovery.']:[],longevityRarity:race?.name==='Giant'||race?.name==='Mink'?'species-dependent':'ordinary'};};
  const mentorEntry=(character,age)=>{const mentor=character.mentor;if(!mentor||mentor.name==='Self-Taught')return [];const months=6+(hash(character.seed,97)%72);const start=Math.max(12,age-Math.ceil(months/12)-1),end=Math.min(age,start+Math.ceil(months/12));return [{mentorId:mentor.id||null,mentorName:mentor.name,startAge:start,endAge:end,durationMonths:months,intensity:months>36?'sustained':'brief',teachings:[],relationship:months>48?'lasting teacher-student bond':'training period',endReason:end>=age?'still training':'completed training',influenceScore:Math.min(100,Math.round(months*1.1)),current:end>=age}];};
  life.create=function(character,overrides={}){
    const regions=V4.database.regions||[]; if(!regions.length)return null;
    const seed=character.seed; const chosen=overrides.currentRegionId||pick(regions,seed,1).id; const childhood=overrides.childhoodRegionId||pick(regions,seed,2).id; const birth=overrides.birthRegionId||childhood;
    const age=Number(overrides.age)||18+(hash(seed,3)%11); const profile=ageProfile(age,character.race); const dream=overrides.dreamId||pick(V4.database.dreams||[{id:'live-freely'}],seed,4).id; const archetype=pick(V4.database.personalityArchetypes||[{id:'restless-explorer',values:['freedom'],fears:['confinement']}],seed,5);
    const traveled=childhood!==chosen; const timeline=[
      {id:`birth-${character.id}`,age:0,yearIndex:0,regionId:birth,category:'origin',title:`Born in ${region(birth)?.name||birth}`,description:'Their life began beside the sea.',consequences:{stats:{},traitsAdded:[],traitsRemoved:[],relationships:[],injuries:[]},source:'generated-life-history'},
      {id:`training-${character.id}`,age:Math.max(10,age-8),yearIndex:1,regionId:childhood,category:'training',title:'Found a reason to train',description:'A personal goal turned ordinary practice into a commitment.',consequences:{stats:{},traitsAdded:[],traitsRemoved:[],relationships:[],injuries:[]},source:'generated-life-history'}
    ];
    if(traveled)timeline.push({id:`travel-${character.id}`,age:Math.max(16,age-3),yearIndex:2,regionId:chosen,category:'voyage',title:`Sailed toward ${region(chosen)?.name||chosen}`,description:'A change of sea brought new risks and opportunities.',consequences:{stats:{},traitsAdded:[],traitsRemoved:[],relationships:[],injuries:[]},source:'generated-life-history'});
    const mentors=overrides.mentorHistory||mentorEntry(character,age); for(const entry of mentors)timeline.push({id:`mentor-${character.id}-${entry.startAge}`,age:entry.startAge,yearIndex:timeline.length,regionId:chosen,category:'mentor',title:`Trained with ${entry.mentorName}`,description:`${entry.intensity==='brief'?'A brief lesson shaped a single part of their path.':'A sustained training period shaped their foundation.'}`,consequences:{stats:{},traitsAdded:[],traitsRemoved:[],relationships:[],mentorStarted:entry.mentorId,mentorEnded:entry.current?null:entry.mentorId,injuries:[]},source:'generated-life-history'});
    return {birthRegionId:birth,childhoodRegionId:childhood,currentRegionId:chosen,age,activeYears:profile.activeYears,startingAge:age,dreamId:dream,coreValues:overrides.coreValues||archetype.values||[],fears:overrides.fears||archetype.fears||[],relationships:overrides.relationships||[],mentorHistory:mentors,timeline:timeline.sort((a,b)=>a.age-b.age),currentGoal:overrides.currentGoal||'Turn a personal dream into a life on the sea.',unresolvedConflict:overrides.unresolvedConflict||'The sea still has not answered every question.'};
  };
  life.ensure=function(character){if(!character.life)character.life=life.create(character)||{};character.ageProfile=character.ageProfile||ageProfile(character.life.age||21,character.race);character.mentorHistory=character.mentorHistory||character.life.mentorHistory||[];return character.life;};
  life.normalizeFruit=function(character){if(!character.fruit)return;character.fruitOrigin=character.fruit.fruitOrigin||'natural-devil-fruit';if(character.fruitOrigin==='smile'){character.fruit.isSmile=true;character.fruit.type=character.fruit.successfulSmile?'Artificial Zoan (SMILE)':'Failed SMILE';character.fruit.baseRollable=false;}};
  life.apply=function(character,overrides){life.ensure(character);life.normalizeFruit(character);return character;};
  const generator=V4.engines.generator;
  if(generator?.generate&&!generator._v55LifeWrapped){const generate=generator.generate;generator.generate=function(overrides,seed,options){return life.apply(generate.call(this,overrides,seed,options));};generator._v55LifeWrapped=true;}
}(window.OnePieceRollV4));

