/* Deterministic, bounded V5.1 Career actions. */
(function (V4) { 'use strict'; const events=V4.engines.progressionEvents=V4.engines.progressionEvents||{}; const seed=(character,state)=>V4.engines.rng.create((Number(character.seed)||1) ^ Math.imul(state.voyageTurn+1,7919));
  const requirementValue=(character,state,key)=>({disciplineMastery:state.experience.discipline||0,speed:character.physical?.speed||0,strength:character.physical?.strength||0,stamina:character.physical?.stamina||0,willpower:character.willpower||0,coordination:character.techniqueAttributes?.coordination||0,observation:character.haki?.obs||0,armament:character.haki?.arm||0,conquerors:character.haki?.coc||0})[key] ?? 0;
  events.techniqueStatus = function(character, techniqueId) { const state=V4.engines.career.ensure(character), technique=(V4.database.techniques||[]).find(entry=>entry.id===techniqueId); if(!technique) return {allowed:false,reasons:['Unknown technique.']}; const known=state.combatProgression.techniqueIds||[]; if(known.includes(techniqueId)) return {allowed:false,reasons:['Already learned.'],technique}; const knownDisciplines=new Set([...(state.combatProgression.foundationIds||[]),...(state.combatProgression.disciplineIds||[])]); const parentOk=(technique.parentDisciplineIds||[]).some(id=>knownDisciplines.has(id)||id==='armament-haki'&&character.haki?.arm>0||id==='fish-man-karate'&&character.race?.id==='fishman'); const reasons=[]; if(!parentOk) reasons.push('A parent foundation or discipline is required.'); for(const [key,minimum] of Object.entries(technique.requirements||{})) if(requirementValue(character,state,key)<minimum) reasons.push(`${key} requires ${minimum}.`); return {allowed:reasons.length===0,reasons,technique}; };
  events.learnTechnique = function(character, techniqueId, route='training') { const status=events.techniqueStatus(character,techniqueId); if(!status.allowed) throw new Error(status.reasons.join(' ')); if(!(status.technique.unlockRoutes||[]).includes(route)) throw new Error('That technique cannot be learned through this route.'); const state=V4.engines.career.ensure(character); state.combatProgression.techniqueIds.push(techniqueId); state.trainingHistory.push({action:'learn-technique',techniqueId,route,turn:state.voyageTurn+1,success:true,message:`Learned ${status.technique.name}.`}); state.voyageTurn++; return status.technique; };
  events.apply = function(character,action,context={}) { const state=V4.engines.career.ensure(character), rng=seed(character,state), exp=state.experience, result={action,turn:state.voyageTurn+1,success:false,message:'',gains:{}}; const limited=(key,current,cap=100)=>Math.max(0,Math.min(cap-current,Math.round(2+rng.next()*5))); const apply=(key,statPath)=>{const amount=limited(key,exp[key]); exp[key]+=amount; result.gains[key]=amount; if(statPath) statPath(amount); result.success=amount>0;};
    if(action==='train-haki'){apply('haki',amount=>{character.haki.obs=Math.min(100,character.haki.obs+amount*.12); character.haki.arm=Math.min(100,character.haki.arm+amount*.12);}); result.message=result.success?'Focused Haki drills improve control, not automatic advanced Haki.':'Haki training has reached its current diminishing-return limit.';}
    else if(action==='train-weapon'){if(!character.weapon) throw new Error('No equipped weapon to train.'); apply('weapon',amount=>{const id=character.weapon.id; state.weaponProgression.masteryByWeaponId[id]=Math.min(100,(state.weaponProgression.masteryByWeaponId[id]||0)+amount*.5);}); result.message='Weapon drills recorded.';}
    else if(action==='train-discipline'){apply('discipline'); result.message='Foundation and discipline practice recorded; techniques still require their own data requirements.';}
    else if(action==='recover'){const amount=3+Math.floor(rng.next()*5); character.physical.recovery=Math.min(100,character.physical.recovery+amount*.2); result.success=true; result.gains.recovery=amount; result.message='Recovery lowers immediate strain and restores readiness.';}
    else if(action==='search-mentor'){const pool=(V4.database.mentors||[]).filter(mentor=>mentor.characterId); const mentor=pool[Math.floor(rng.next()*pool.length)]; result.success=!!mentor; result.mentorProfileId=mentor?.profileId; if(mentor){const relationship={mentorId:mentor.id,mentorProfileId:mentor.profileId,characterId:mentor.characterId,startedTurn:result.turn,endsTurn:result.turn+3,status:'available-temporary-training',source:mentor.source||'canon'}; state.temporaryMentorHistory.push(relationship); character.mentorHistory=character.mentorHistory||[]; character.mentorHistory.push(relationship); result.message=`A temporary training contact is available: ${mentor.name}.`; } else result.message='No suitable mentor contact found.';}
    else if(action==='explore-fruit'){result.success=false; result.message='No fruit was found. Devil Fruit acquisition remains rare and requires an explicit eligible world event.';}
    else if(action==='challenge-rival'){apply('combat'); state.battleHistory.push({turn:result.turn,type:'rival-challenge',outcome:result.success?'learned-from-clash':'withdrawn'}); result.message=result.success?'The rival clash teaches practical combat experience.':'The rival offered no useful opening.';}
    else if(action==='enlist-marines'){state.careerPath='marine'; state.factionRank=state.factionRank||'Recruit'; result.success=true; result.message='You enter the Marine career track. Promotions require later mission and service systems.';}
    else if(action==='seek-cipher-pol'){state.careerPath='cipher-pol'; state.factionRank=state.factionRank||'Candidate'; result.success=true; result.message='You enter the Cipher Pol candidate track. Covert assignments are deferred to the Battle/Career pass.';}
    else throw new Error('Unknown Career action.'); state.voyageTurn++; state.trainingHistory.push(result); if(result.success && ['challenge-rival','enlist-marines','seek-cipher-pol'].includes(action) && V4.engines.bounty?.calculate){const next=V4.engines.bounty.calculate(character);const amount=Number(next.displayedAmount||next.amount||0), previous=state.bountyHistory[state.bountyHistory.length-1]?.amount||0;character.bounty=next;if(amount!==previous)state.bountyHistory.push({turn:state.voyageTurn,amount,reason:action});} return result; };
}(window.OnePieceRollV4));

