/* V5.5 rarity language: estimates are clear about conditional and authored outcomes. */
(function(V4){'use strict';const rarity=V4.engines.rarity=V4.engines.rarity||{};
  const finite=v=>Math.max(1e-12,Math.min(1,Number(v)||1)), odds=v=>v<1e-9?'Less than 1 in 1 billion':v>=1?'Common':`About 1 in ${Math.round(1/v).toLocaleString()}`;
  const percent=v=>v<1e-9?'Less than 0.0000001%':`${(v*100).toFixed(v<.01?3:2)}%`, mentors={legendary:.0045,elite:.079,notable:.619,'self-taught':.297},grades={Supreme:.0325,Great:.193,Skillful:.193,Standard:.176,None:.406};
  const fruit=f=>{if(!f)return .3;const w={Paramecia:15,Zoan:12,'Ancient Zoan':4,'Mythical Zoan':1,Logia:3},pool=(V4.database.fruits||[]).filter(x=>x.baseRollable!==false),weight=x=>(w[x.type]||10)*Math.max(0,Number(x.rollWeight??1)),total=pool.reduce((s,x)=>s+weight(x),0);return total?.7*weight(f)/total:.001;};
  const add=(a,label,chance,on)=>on&&a.push({label,chance:finite(chance),percent:percent(finite(chance)),odds:odds(finite(chance))});
  rarity.analyze=function(c){const mode=c.generationMode||'standard-adventure',origin=c.creation?.origin;if(origin==='canon-preset'||origin==='oc-preset'||c.presetOf||c.generationProvenance?.presetProfileId)return{entries:[],probability:null,percent:'Not applicable',odds:origin==='oc-preset'?'Authored original character':'Curated canon persona',rank:'Authored / Not Applicable',mode,source:'not-applicable',methodology:'This is an authored preset, not a natural roll.'};if(['unrestricted-sandbox','guided-sandbox'].includes(mode))return{entries:[],probability:null,percent:'Not applicable',odds:mode==='guided-sandbox'?'Conditional build estimate only':'Natural-roll rarity does not apply',rank:'Authored / Not Applicable',mode,source:mode==='guided-sandbox'?'conditional-estimate':'not-applicable',methodology:'Selected and guaranteed Sandbox properties cannot be presented as a natural-roll chance.'};
    const e=[];add(e,`${c.mentor?.tier||'Unknown'} Mentor`,mentors[c.mentor?.tier]||.5,!!c.mentor&&c.mentor.name!=='Self-Taught');add(e,c.fruit?`${c.fruit.displayAlias||c.fruit.name} (${c.fruit.rarityTier||c.fruit.type})`:'No Devil Fruit',fruit(c.fruit),true);if(c.weapon)add(e,`${c.weapon.grade} Grade Weapon`,grades[c.weapon.grade]||.25,true);add(e,c.haki?.hasAdvCoc?'Advanced Conqueror Haki':c.haki?.hasAdvObs?'Future Sight':c.haki?.hasAdvArm?'Advanced Armament':c.haki?.hasCoc?'Conqueror Haki':'Haki Profile',c.haki?.hasAdvCoc?.0008:c.haki?.hasAdvObs?.0018:c.haki?.hasAdvArm?.003:c.haki?.hasCoc?.035:.55,true);if(c.hasAwakened)add(e,'Devil Fruit Awakening',.00005,true);for(const t of c.traits||[])add(e,t.name,t.rarity||.25,true);if((c.synergyBonus||0)>=60)add(e,'Perfect Synergy',.00397,true);if((c.combatRating||0)>=150)add(e,'Pirate King-scale combat',.00001,true);else if((c.combatRating||0)>=120)add(e,'Emperor-scale combat',.00008,true);let p=e.reduce((n,x)=>n*x.chance,1);if(mode==='standard-adventure')p=Math.min(1,p*1.35);return{entries:e,probability:p,percent:percent(p),odds:odds(p),rank:p<1e-9?'World Anomaly':p<1e-6?'Mythic':p<1e-4?'Legendary':p<.01?'Exceptional':p<.12?'Rare':'Uncommon',mode,source:'conditional-estimate',sampleSize:100000,confidence:'estimated',correlatedEvents:['mentor and disciplines','Haki and advanced states','Voyage Luck and opportunity packages'],methodology:'Estimated combination rarity. Linked outcomes are not treated as independent measured events; this is not an exact probability.'};};
}(window.OnePieceRollV4));

