/* Additional reviewed Battle roster. Numbers are curated simulator interpretations. */
(function(V4){
  'use strict';
  const h=(obs,arm,coc,advancedObservation=false,advancedArmament=false,conquerorsCoating=false)=>({observation:obs,armament:arm,conquerors:coc,advancedObservation,advancedArmament,conquerorsCoating});
  const p=(id,characterId,name,era,balanceBand,physical,mental,willpower,haki,fruitId,foundationIds,disciplineIds,options={})=>({id,characterId,name,era,source:options.source||'canon',spoilerEra:'late-wano',physical,mental,willpower,haki,fruitId,secondaryFruitIds:options.secondaryFruitIds||[],fruitMastery:fruitId?(options.fruitMastery??88):null,weaponMastery:options.weaponMastery??82,weaponIds:options.weaponIds||[],foundationIds,disciplineIds,techniqueIds:options.techniqueIds||[],advancedStateIds:options.advancedStateIds||[],behaviorProfileIds:[options.behavior||'ai-balanced'],balanceBand,confidence:'curated',awakened:!!options.awakened,specialRules:options.specialRules||[],evidenceNotes:['Curated simulator interpretation; not an official numeric power ranking.',...(options.notes||[])]});
  const profiles=[
    p('combat-portgas-d-ace-wano-reference','portgas-d-ace','Portgas D. Ace','marineford','commander',{strength:81,speed:87,durability:76,stamina:90,recovery:66},{knowledge:61,battleIQ:84,creativity:83,leadership:76},92,h(true,true,true),'mera-mera-no-mi',['basic-martial-arts'],[],{fruitMastery:88,behavior:'ai-fiery-protector'}),
    p('combat-eustass-kid-late-wano','eustass-kid','Eustass Kid','late-wano','commander',{strength:89,speed:75,durability:92,stamina:94,recovery:69},{knowledge:62,battleIQ:84,creativity:90,leadership:82},94,h(true,true,true),'jiki-jiki-no-mi',['brawling'],[],{fruitMastery:96,awakened:true,behavior:'ai-aggressive-captain'}),
    p('combat-crocodile-late-wano','crocodile','Crocodile','late-wano','commander',{strength:73,speed:79,durability:74,stamina:85,recovery:57},{knowledge:91,battleIQ:92,creativity:88,leadership:82},87,h(false,false,false),'suna-suna-no-mi',['brawling'],[],{fruitMastery:94,behavior:'ai-desert-strategist'}),
    p('combat-donquixote-doflamingo-late-wano','donquixote-doflamingo','Donquixote Doflamingo','dressrosa','commander',{strength:86,speed:88,durability:88,stamina:92,recovery:65},{knowledge:86,battleIQ:91,creativity:95,leadership:91},95,h(true,true,true),'ito-ito-no-mi',['brawling'],[],{fruitMastery:98,awakened:true,behavior:'ai-cruel-controller'}),
    p('combat-marco-late-wano','marco','Marco','late-wano','commander',{strength:86,speed:92,durability:89,stamina:94,recovery:100},{knowledge:80,battleIQ:91,creativity:76,leadership:86},91,h(true,true,false),'tori-tori-no-mi-model-phoenix',['basic-martial-arts'],[],{fruitMastery:98,behavior:'ai-regenerative-guardian'}),
    p('combat-kaido-late-wano','kaido','Kaido','late-wano','emperor',{strength:104,speed:94,durability:110,stamina:110,recovery:84},{knowledge:67,battleIQ:96,creativity:78,leadership:93},108,h(true,true,true,true,true,true),'uo-uo-no-mi-model-seiryu',['heavy-weapon-fighting'],['kanabo-style'],{fruitMastery:100,weaponMastery:98,weaponIds:['hassaikai'],behavior:'ai-overwhelming-emperor',notes:['Represents Kaido during the Wano rooftop battle.']}),
    p('combat-charlotte-linlin-late-wano','charlotte-linlin','Charlotte Linlin','late-wano','emperor',{strength:103,speed:82,durability:109,stamina:108,recovery:80},{knowledge:68,battleIQ:89,creativity:90,leadership:94},106,h(true,true,true,false,true,true),'soru-soru-no-mi',['swordsmanship'],['one-sword-style'],{fruitMastery:100,weaponMastery:94,weaponIds:['napoleon'],behavior:'ai-chaotic-emperor'}),
    p('combat-shanks-late-wano','shanks','Shanks','late-wano','emperor',{strength:99,speed:103,durability:93,stamina:104,recovery:74},{knowledge:83,battleIQ:104,creativity:86,leadership:105},110,h(true,true,true,false,true,true),null,['swordsmanship'],['one-sword-style'],{weaponMastery:100,weaponIds:['gryphon'],behavior:'ai-haki-emperor'}),
    p('combat-edward-newgate-marineford','edward-newgate','Edward Newgate','marineford','emperor',{strength:105,speed:77,durability:106,stamina:101,recovery:55},{knowledge:78,battleIQ:98,creativity:78,leadership:108},109,h(true,true,true,false,true,true),'gura-gura-no-mi',['polearm-fighting'],[],{fruitMastery:100,weaponMastery:100,weaponIds:['murakumogiri'],behavior:'ai-protective-emperor',notes:['Represents the Marineford-era fighter, not an invented prime-age numeric profile.']}),
    p('combat-monkey-d-garp-late-wano','monkey-d-garp','Monkey D. Garp','late-wano','admiral',{strength:104,speed:94,durability:102,stamina:105,recovery:78},{knowledge:71,battleIQ:101,creativity:72,leadership:96},108,h(true,true,false,false,true,false),null,['brawling'],[],{behavior:'ai-haki-brawler'}),
    p('combat-sakazuki-late-wano','sakazuki','Sakazuki','late-wano','fleet-admiral',{strength:98,speed:88,durability:102,stamina:105,recovery:71},{knowledge:82,battleIQ:99,creativity:79,leadership:101},104,h(true,true,false,false,true,false),'magu-magu-no-mi',['brawling'],[],{fruitMastery:100,behavior:'ai-relentless-magma'}),
    p('combat-kuzan-late-wano','kuzan','Kuzan','late-wano','admiral',{strength:92,speed:91,durability:96,stamina:104,recovery:74},{knowledge:86,battleIQ:98,creativity:91,leadership:84},99,h(true,true,false,false,true,false),'hie-hie-no-mi',['brawling'],[],{fruitMastery:100,behavior:'ai-patient-freezer'}),
    p('combat-borsalino-late-wano','borsalino','Borsalino','late-wano','admiral',{strength:88,speed:110,durability:91,stamina:101,recovery:70},{knowledge:80,battleIQ:97,creativity:87,leadership:82},96,h(true,true,false,false,true,false),'pika-pika-no-mi',['basic-martial-arts'],[],{fruitMastery:99,behavior:'ai-light-speed-zoner'}),
    p('combat-silvers-rayleigh-late-wano','silvers-rayleigh','Silvers Rayleigh','late-wano','admiral',{strength:94,speed:97,durability:91,stamina:96,recovery:71},{knowledge:98,battleIQ:104,creativity:90,leadership:93},106,h(true,true,true,false,true,false),null,['swordsmanship'],['one-sword-style'],{weaponMastery:99,behavior:'ai-master-teacher'}),
    p('combat-marshall-d-teach-late-wano','marshall-d-teach','Marshall D. Teach','late-wano','emperor',{strength:99,speed:78,durability:107,stamina:108,recovery:73},{knowledge:91,battleIQ:96,creativity:93,leadership:99},102,h(true,true,false),'yami-yami-no-mi',['brawling'],[],{secondaryFruitIds:['gura-gura-no-mi'],fruitMastery:98,behavior:'ai-opportunistic-darkness',specialRules:['multiple-devil-fruit-exception','darkness-nullification'],notes:['Canon confirms the two powers; the mechanism that makes this possible remains unknown.']}),
    p('combat-goose-eclipsed-goddess','goose-eclipsed-goddess','Goose — The Eclipsed Goddess','alternate-world','pirate-king-plus',{strength:112,speed:124,durability:108,stamina:118,recovery:96},{knowledge:101,battleIQ:116,creativity:122,leadership:92},122,h(true,true,true,true,true,false),'tori-tori-no-mi-model-lunar-abyssal-goose-goddess',['basic-martial-arts'],[],{source:'fan',fruitMastery:100,awakened:true,behavior:'ai-eclipsed-goddess',advancedStateIds:['goose-full-alter','goose-ishtar-pact'],specialRules:['localized-singularity','eclipse-inversion','maanna-wings','eclipse-eyes','alter-hatred-growth'],notes:['User-provided OC preset. Standard seawater and Seastone weaknesses remain active.','Large singularities cost substantial stamina; inversion cannot freely bypass stronger Haki.']})
  ];
  const existing=new Set((V4.database.combatProfiles||[]).map(profile=>profile.id));for(const profile of profiles)if(!existing.has(profile.id))V4.database.combatProfiles.push(profile);
}(window.OnePieceRollV4));


