/* Authoritative fruits database. */
(function (V4) {
  'use strict';
  const slug = value => String(value).toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
  const sourceFor = entry => entry.source || entry.src || 'canon';
  const rawEntries = [
    { name: "Gomu Gomu no Mi", type: "Paramecia", power: 90, diff: 80, vers: 95, awk: 100, src: "canon", desc: "Turns the user's body into rubber, immune to blunt trauma and electricity.", strengths: ["Immune to blunt attacks and electricity","Extreme elasticity enables creative attacks","Gear transformations multiply combat power"], weaknesses: ["Vulnerable to sharp, piercing attacks","Requires high creativity to use effectively","Gear forms drain stamina rapidly"], utility: 70 },
    { name: "Mera Mera no Mi", type: "Logia", power: 85, diff: 50, vers: 80, awk: 85, src: "canon", desc: "Grants the power to create, control, and become fire.", strengths: ["Logia intangibility against non-Haki users","Devastating area-of-effect attacks","Fire propulsion for mobility"], weaknesses: ["Outclassed by magma-based abilities","Collateral damage hard to control","Useless underwater"], utility: 55 },
    { name: "Ope Ope no Mi", type: "Paramecia", power: 95, diff: 95, vers: 100, awk: 95, src: "canon", desc: "Creates a spherical 'Room' where the user controls everything — space, biology, objects.", strengths: ["Near-total spatial manipulation inside Room","Can perform impossible surgeries","Personality and soul transfer"], weaknesses: ["Extremely stamina-intensive","Requires genius-level IQ to exploit","Room has a fixed radius"], utility: 100 },
    { name: "Tori Tori no Mi, Model: Phoenix", type: "Mythical Zoan", power: 88, diff: 65, vers: 70, awk: 90, src: "canon", desc: "Transforms the user into a phoenix with regenerative blue flames.", strengths: ["Regenerative flames heal any wound","Flight capability","Blue fire can heal allies"], weaknesses: ["Regeneration has stamina limits","Offensive power is moderate","Flames don't burn — limited offense"], utility: 80 },
    { name: "Bara Bara no Mi", type: "Paramecia", power: 35, diff: 20, vers: 45, awk: 50, src: "canon", desc: "Allows the user to split their body into pieces and control them telekinetically.", strengths: ["Complete immunity to slashing attacks","Body parts fly independently","Very easy to activate"], weaknesses: ["Low raw offensive power","Feet must stay grounded","Pieces can be restrained individually"], utility: 40 },
    { name: "Hana Hana no Mi", type: "Paramecia", power: 75, diff: 60, vers: 90, awk: 85, src: "canon", desc: "Sprouts body parts on any surface within range." },
    { name: "Doku Doku no Mi", type: "Paramecia", power: 95, diff: 70, vers: 65, awk: 90, src: "canon", desc: "Generates and controls deadly, customizable poisons." },
    { name: "Gura Gura no Mi", type: "Paramecia", power: 100, diff: 60, vers: 50, awk: 95, src: "canon", desc: "Creates world-ending shockwaves." },
    { name: "Ito Ito no Mi", type: "Paramecia", power: 85, diff: 85, vers: 95, awk: 95, src: "canon", desc: "Razor strings for combat, puppetry, and control." },
    { name: "Bari Bari no Mi", type: "Paramecia", power: 80, diff: 40, vers: 60, awk: 70, src: "canon", desc: "Creates indestructible barriers." },
    { name: "Hobi Hobi no Mi", type: "Paramecia", power: 100, diff: 20, vers: 40, awk: 0, src: "canon", desc: "Turns touched victims into toys, erasing memory." },
    { name: "Soru Soru no Mi", type: "Paramecia", power: 95, diff: 80, vers: 90, awk: 90, src: "canon", desc: "Manipulates souls, animating objects." },
    { name: "Mochi Mochi no Mi", type: "Paramecia", power: 85, diff: 90, vers: 90, awk: 95, src: "canon", desc: "Special Paramecia generating sticky mochi." },
    { name: "Nikyu Nikyu no Mi", type: "Paramecia", power: 90, diff: 75, vers: 90, awk: 85, src: "canon", desc: "Paw pads repel anything." },
    { name: "Mero Mero no Mi", type: "Paramecia", power: 90, diff: 50, vers: 60, awk: 80, src: "canon", desc: "Petrifies those who feel attraction." },
    { name: "Kage Kage no Mi", type: "Paramecia", power: 80, diff: 70, vers: 85, awk: 85, src: "canon", desc: "Manifests and steals shadows." },
    { name: "Horo Horo no Mi", type: "Paramecia", power: 85, diff: 60, vers: 75, awk: 70, src: "canon", desc: "Ghosts that sap the will to fight." },
    { name: "Jiki Jiki no Mi", type: "Paramecia", power: 90, diff: 80, vers: 85, awk: 95, src: "canon", desc: "Total magnetic manipulation." },
    { name: "Zushi Zushi no Mi", type: "Paramecia", power: 95, diff: 80, vers: 85, awk: 90, src: "canon", desc: "Summons meteors and bends gravity." },
    { name: "Bisu Bisu no Mi", type: "Paramecia", power: 85, diff: 75, vers: 80, awk: 85, src: "canon", desc: "Generates infinite hardened biscuit." },
    { name: "Doru Doru no Mi", type: "Paramecia", power: 65, diff: 60, vers: 85, awk: 75, src: "canon", desc: "Creates candle wax harder than steel." },
    { name: "Horu Horu no Mi", type: "Paramecia", power: 75, diff: 80, vers: 90, awk: 80, src: "canon", desc: "Hormones that reshape bodies." },
    { name: "Neko Neko no Mi, Model: Leopard", type: "Zoan", power: 75, diff: 60, vers: 50, awk: 85, src: "canon", desc: "Massively boosts speed, agility, bloodlust." },
    { name: "Ryu Ryu no Mi, Model: Allosaurus", type: "Ancient Zoan", power: 80, diff: 60, vers: 50, awk: 85, src: "canon", desc: "Transforms into a ferocious Allosaurus." },
    { name: "Ryu Ryu no Mi, Model: Pteranodon", type: "Ancient Zoan", power: 85, diff: 70, vers: 65, awk: 85, src: "canon", desc: "High-speed flight and devastating beak." },
    { name: "Zou Zou no Mi, Model: Mammoth", type: "Ancient Zoan", power: 85, diff: 50, vers: 40, awk: 85, src: "canon", desc: "Incredible endurance and crushing power." },
    { name: "Hito Hito no Mi, Model: Daibutsu", type: "Mythical Zoan", power: 95, diff: 80, vers: 75, awk: 95, src: "canon", desc: "Giant golden Buddha with shockwave palms." },
    { name: "Uo Uo no Mi, Model: Seiryu", type: "Mythical Zoan", power: 100, diff: 85, vers: 80, awk: 100, src: "canon", desc: "Colossal Azure Dragon of legend." },
    { name: "Inu Inu no Mi, Model: Kyubi no Kitsune", type: "Mythical Zoan", power: 85, diff: 80, vers: 90, awk: 90, src: "canon", desc: "Nine-tailed fox with perfect illusions." },
    { name: "Suna Suna no Mi", type: "Logia", power: 85, diff: 75, vers: 85, awk: 90, src: "canon", desc: "Sand that drains moisture." },
    { name: "Goro Goro no Mi", type: "Logia", power: 95, diff: 65, vers: 90, awk: 95, src: "canon", desc: "Create, control, and become lightning." },
    { name: "Hie Hie no Mi", type: "Logia", power: 95, diff: 75, vers: 90, awk: 95, src: "canon", desc: "Create, control, and become ice." },
    { name: "Yami Yami no Mi", type: "Logia", power: 100, diff: 80, vers: 85, awk: 95, src: "canon", desc: "Nullifies other fruits on contact." },
    { name: "Pika Pika no Mi", type: "Logia", power: 95, diff: 70, vers: 85, awk: 95, src: "canon", desc: "Create, control, and become light." },
    { name: "Magu Magu no Mi", type: "Logia", power: 100, diff: 65, vers: 75, awk: 95, src: "canon", desc: "Unrivaled offensive power; living magma." },
    { name: "Gasu Gasu no Mi", type: "Logia", power: 90, diff: 85, vers: 90, awk: 90, src: "canon", desc: "Gas manipulation capable of suffocating a battlefield." },
    { name: "Mizu Mizu no Mi", type: "Logia", power: 85, diff: 90, vers: 90, awk: 90, src: "fan", desc: "Freshwater Logia. Hard to master." },
    { name: "Kaze Kaze no Mi", type: "Logia", power: 90, diff: 75, vers: 95, awk: 90, src: "fan", desc: "Wind Logia. Razor gusts and flight." },
    { name: "Purazuma Purazuma no Mi", type: "Logia", power: 95, diff: 85, vers: 85, awk: 95, src: "fan", desc: "Plasma Logia. Searing ionized gas." },
    { name: "Chi Chi no Mi", type: "Paramecia", power: 85, diff: 95, vers: 85, awk: 90, src: "fan", desc: "Blood manipulation. Harden blood into weapons." },
    { name: "San San no Mi", type: "Paramecia", power: 90, diff: 60, vers: 60, awk: 80, src: "fan", desc: "Acid Paramecia. Melts through anything." },
    { name: "Tanzo Tanzo no Mi", type: "Paramecia", power: 65, diff: 80, vers: 90, awk: 80, src: "fan", desc: "Forge Paramecia. Eat and reshape metal." },
    { name: "Sozo Sozo no Mi", type: "Paramecia", power: 70, diff: 95, vers: 100, awk: 90, src: "fan", desc: "Creation Paramecia. Draw objects into reality." },
    { name: "Esupa Esupa no Mi", type: "Paramecia", power: 85, diff: 85, vers: 95, awk: 90, src: "fan", desc: "Esper Paramecia. Telekinesis and psychic blasts." },
    { name: "Hito Hito no Mi, Model: Vampire", type: "Mythical Zoan", power: 90, diff: 75, vers: 85, awk: 90, src: "fan", desc: "Drains life force to heal." },
    { name: "Tori Tori no Mi, Model: Thunderbird", type: "Mythical Zoan", power: 90, diff: 80, vers: 80, awk: 95, src: "fan", desc: "Storm-bird conjuring electrical fronts." },
    { name: "Hebi Hebi no Mi, Model: Hydra", type: "Mythical Zoan", power: 95, diff: 85, vers: 75, awk: 95, src: "fan", desc: "Regenerating heads and toxic breath." },
    { name: "Inu Inu no Mi, Model: Fenrir", type: "Mythical Zoan", power: 90, diff: 70, vers: 60, awk: 90, src: "fan", desc: "Colossal wolf with freezing aura." },
    { name: "Saru Saru no Mi, Model: Sun Wukong", type: "Mythical Zoan", power: 95, diff: 90, vers: 90, awk: 95, src: "fan", desc: "Monkey king form with clones and size alteration." },
    { name: "Kame Kame no Mi, Model: Genbu", type: "Mythical Zoan", power: 90, diff: 75, vers: 70, awk: 95, src: "fan", desc: "Black Tortoise with impenetrable defenses." },

    // V4.5 batch 01 — canon, spoiler-safe powers seen before late Wano.
    { id: 'sube-sube-no-mi', name: 'Sube Sube no Mi', type: 'Paramecia', power: 32, diff: 25, vers: 42, awk: 55, source: 'canon', desc: 'Makes the user’s body exceptionally smooth, causing many attacks to slip away.', description: 'Makes the user’s body exceptionally smooth, causing many attacks to slip away.', strengths: ['Reduces friction against ordinary attacks', 'Improves evasive movement'], weaknesses: ['Does not remove standard Devil Fruit weaknesses', 'Offers limited direct offense without training'], utility: 38, tags: ['paramecia', 'evasion', 'body-alteration'] },
    { id: 'bomu-bomu-no-mi', name: 'Bomu Bomu no Mi', type: 'Paramecia', power: 67, diff: 48, vers: 70, awk: 70, source: 'canon', desc: 'Lets the user cause parts of their own body to explode without being harmed by the blast.', description: 'Lets the user cause parts of their own body to explode without being harmed by the blast.', strengths: ['Explosive strikes and projectiles', 'Body is safe from its own explosions'], weaknesses: ['Collateral damage is difficult to control', 'Standard Devil Fruit weaknesses still apply'], utility: 48, tags: ['paramecia', 'explosive', 'combat'] },
    { id: 'kiro-kiro-no-mi', name: 'Kiro Kiro no Mi', type: 'Paramecia', power: 48, diff: 34, vers: 62, awk: 60, source: 'canon', desc: 'Allows the user to alter their body weight while keeping the same size.', description: 'Allows the user to alter their body weight while keeping the same size.', strengths: ['Can become light for mobility', 'Can add crushing force to a fall or strike'], weaknesses: ['Requires positioning to use its weight safely', 'Standard Devil Fruit weaknesses still apply'], utility: 55, tags: ['paramecia', 'weight', 'mobility'] },
    { id: 'baku-baku-no-mi', name: 'Baku Baku no Mi', type: 'Paramecia', power: 58, diff: 65, vers: 82, awk: 72, source: 'canon', desc: 'Lets the user eat objects and alter their body using what was consumed.', description: 'Lets the user eat objects and alter their body using what was consumed.', strengths: ['Can consume and incorporate materials', 'Highly adaptable body alteration'], weaknesses: ['Needs suitable material to exploit fully', 'Standard Devil Fruit weaknesses still apply'], utility: 72, tags: ['paramecia', 'consumption', 'body-alteration'] },
    { id: 'mane-mane-no-mi', name: 'Mane Mane no Mi', type: 'Paramecia', power: 28, diff: 42, vers: 84, awk: 65, source: 'canon', desc: 'Allows the user to copy the appearance and voice of a person whose face they have touched.', description: 'Allows the user to copy the appearance and voice of a person whose face they have touched.', strengths: ['Excellent disguise and infiltration tool', 'Can imitate a copied voice'], weaknesses: ['Copies appearance rather than combat ability', 'Requires prior physical contact with the target'], utility: 90, tags: ['paramecia', 'disguise', 'infiltration'] },
    { id: 'supa-supa-no-mi', name: 'Supa Supa no Mi', type: 'Paramecia', power: 72, diff: 54, vers: 63, awk: 74, source: 'canon', desc: 'Lets the user turn body parts into steel blades for offense and defense.', description: 'Lets the user turn body parts into steel blades for offense and defense.', strengths: ['Creates blades from the body', 'Resists ordinary slashing attacks'], weaknesses: ['Strong enough cuts can still break its defense', 'Standard Devil Fruit weaknesses still apply'], utility: 45, tags: ['paramecia', 'blade', 'body-alteration'] },
    { id: 'toge-toge-no-mi', name: 'Toge Toge no Mi', type: 'Paramecia', power: 55, diff: 38, vers: 56, awk: 66, source: 'canon', desc: 'Allows the user to grow sharp spikes from their body.', description: 'Allows the user to grow sharp spikes from their body.', strengths: ['Adds reach and damage to close combat', 'Useful for climbing and defense'], weaknesses: ['Relies on close range', 'Standard Devil Fruit weaknesses still apply'], utility: 40, tags: ['paramecia', 'spikes', 'body-alteration'] },
    { id: 'ori-ori-no-mi', name: 'Ori Ori no Mi', type: 'Paramecia', power: 50, diff: 52, vers: 76, awk: 68, source: 'canon', desc: 'Creates iron restraints from the user’s body to bind targets.', description: 'Creates iron restraints from the user’s body to bind targets.', strengths: ['Strong capture and restraint utility', 'Can form shackles and bars quickly'], weaknesses: ['Capture still depends on landing the bind', 'Standard Devil Fruit weaknesses still apply'], utility: 72, tags: ['paramecia', 'restraint', 'capture'] },
    { id: 'bane-bane-no-mi', name: 'Bane Bane no Mi', type: 'Paramecia', power: 52, diff: 38, vers: 64, awk: 68, source: 'canon', desc: 'Turns the user’s legs into springs for high-speed rebounds and jumping attacks.', description: 'Turns the user’s legs into springs for high-speed rebounds and jumping attacks.', strengths: ['Rapid rebounds and long jumps', 'Adds momentum to kicks'], weaknesses: ['Best at movement and impact rather than control', 'Standard Devil Fruit weaknesses still apply'], utility: 52, tags: ['paramecia', 'spring', 'mobility'] },
    { id: 'noro-noro-no-mi', name: 'Noro Noro no Mi', type: 'Paramecia', power: 46, diff: 58, vers: 80, awk: 70, source: 'canon', desc: 'Emits beams that dramatically slow whatever they strike for a short time.', description: 'Emits beams that dramatically slow whatever they strike for a short time.', strengths: ['Creates openings by slowing targets', 'Useful at range and for setup'], weaknesses: ['Requires a successful beam hit', 'Standard Devil Fruit weaknesses still apply'], utility: 75, tags: ['paramecia', 'slow', 'ranged'] },
    { id: 'doa-doa-no-mi', name: 'Doa Doa no Mi', type: 'Paramecia', power: 35, diff: 62, vers: 92, awk: 70, source: 'canon', desc: 'Allows the user to open doorways through surfaces and even the air for travel and infiltration.', description: 'Allows the user to open doorways through surfaces and even the air for travel and infiltration.', strengths: ['Exceptional movement and infiltration', 'Can confuse or trap opponents with doors'], weaknesses: ['Not primarily a direct damage ability', 'Standard Devil Fruit weaknesses still apply'], utility: 96, tags: ['paramecia', 'door', 'infiltration'] },
    { id: 'awa-awa-no-mi', name: 'Awa Awa no Mi', type: 'Paramecia', power: 44, diff: 60, vers: 78, awk: 70, source: 'canon', desc: 'Creates cleansing bubbles that can weaken opponents and make surfaces slick.', description: 'Creates cleansing bubbles that can weaken opponents and make surfaces slick.', strengths: ['Can reduce an opponent’s strength through contact', 'Creates difficult terrain'], weaknesses: ['Requires careful timing and bubble contact', 'Standard Devil Fruit weaknesses still apply'], utility: 72, tags: ['paramecia', 'bubble', 'debuff'] },
    { id: 'yomi-yomi-no-mi', name: 'Yomi Yomi no Mi', type: 'Paramecia', power: 40, diff: 75, vers: 78, awk: 65, source: 'canon', desc: 'Allows the user’s soul to return once after death; its wider soul abilities require experience and training.', description: 'Allows the user’s soul to return once after death; its wider soul abilities require experience and training.', strengths: ['A single return from death', 'Potential for soul-based utility after mastery'], weaknesses: ['Its core effect does not prevent standard Devil Fruit weaknesses', 'Much of its value requires unusual circumstances'], utility: 68, tags: ['paramecia', 'soul', 'resurrection'] }
  ]
;
  const usedIds = new Set();
  const stableId = entry => { const base = entry.id || slug(entry.name); const candidate = usedIds.has(base) ? `${base}-${entry.power}-${entry.diff}-${entry.vers}-${entry.awk}` : base; usedIds.add(candidate); return candidate; };
  V4.database.fruits = rawEntries.map(entry => { const source = sourceFor(entry); return { ...entry, id: stableId(entry), source, canonicalIdentity: entry.canonicalIdentity || `${slug(entry.name)}:${source}`, desc: entry.desc || entry.description, description: entry.description || entry.desc, tags: entry.tags || [entry.type.toLowerCase()], rollWeight: entry.rollWeight ?? 1, baseRollable: entry.baseRollable ?? true }; });
}(window.OnePieceRollV4));


