/* V4.3 combat progression catalog. Foundations are broad; disciplines, techniques, and states require access. */
(function (V4) {
  'use strict';
  const styles = [
    { id: 'brawling', name: 'Brawling', type: 'brawl', power: 55, desc: 'Practical striking, grappling, and improvised fighting without formal specialization.', source: 'expanded', progressionType: 'foundation', parentIds: [], accessRequirements: {}, baseRollable: true, weaponRequirements: null, tags: ['foundation', 'brawl'] },
    { id: 'basic-martial-arts', name: 'Basic Martial Arts', type: 'martial', power: 50, desc: 'Broad body mechanics, guards, striking, and evasive movement.', source: 'expanded', progressionType: 'foundation', parentIds: [], accessRequirements: {}, baseRollable: true, weaponRequirements: null, tags: ['foundation', 'martial'] },
    { id: 'swordsmanship', name: 'Swordsmanship', type: 'sword', power: 50, desc: 'Foundational blade footwork, guards, and practical cuts.', source: 'expanded', progressionType: 'foundation', parentIds: [], accessRequirements: {}, baseRollable: true, weaponRequirements: { family: 'blade', minimum: 1, maximum: 1 }, tags: ['foundation', 'blade'] },
    { id: 'marksmanship', name: 'Marksmanship', type: 'shoot', power: 48, desc: 'Common firearm training in aim, cover, reload discipline, and range judgment.', source: 'expanded', progressionType: 'foundation', parentIds: [], accessRequirements: {}, baseRollable: true, weaponRequirements: { family: 'firearm', minimum: 1, maximum: 1 }, tags: ['foundation', 'firearm'] },
    { id: 'heavy-weapon-fighting', name: 'Heavy Weapon Fighting', type: 'brawl', power: 50, desc: 'Blunt-force fundamentals using weight, leverage, and committed strikes.', source: 'expanded', progressionType: 'foundation', parentIds: [], accessRequirements: {}, baseRollable: true, weaponRequirements: { family: 'club', minimum: 1, maximum: 1 }, tags: ['foundation', 'club'] },
    { id: 'polearm-fighting', name: 'Polearm Fighting', type: 'brawl', power: 50, desc: 'Reach-focused thrusts, sweeps, and formation control.', source: 'expanded', progressionType: 'foundation', parentIds: [], accessRequirements: {}, baseRollable: true, weaponRequirements: { family: 'polearm', minimum: 1, maximum: 1 }, tags: ['foundation', 'polearm'] },
    { id: 'staff-fighting', name: 'Staff Fighting', type: 'brawl', power: 46, desc: 'Two-handed defense, distance control, and redirection.', source: 'expanded', progressionType: 'foundation', parentIds: [], accessRequirements: {}, baseRollable: true, weaponRequirements: { family: 'staff', minimum: 1, maximum: 1 }, tags: ['foundation', 'staff'] },
    { id: 'knife-fighting', name: 'Knife Fighting', type: 'sword', power: 44, desc: 'Close-range blade movement, feints, and counters.', source: 'expanded', progressionType: 'foundation', parentIds: [], accessRequirements: {}, baseRollable: true, weaponRequirements: { family: 'dagger', minimum: 1, maximum: 2 }, tags: ['foundation', 'dagger'] },
    { id: 'axe-fighting', name: 'Axe Fighting', type: 'brawl', power: 51, desc: 'Deliberate chopping attacks with disciplined recovery.', source: 'expanded', progressionType: 'foundation', parentIds: [], accessRequirements: {}, baseRollable: true, weaponRequirements: { family: 'axe', minimum: 1, maximum: 1 }, tags: ['foundation', 'axe'] },
    { id: 'sky-combat', name: 'Sky Combat', type: 'brawl', power: 48, desc: 'Practical movement and tool use shaped by Sky Island conditions.', source: 'expanded', progressionType: 'foundation', parentIds: [], accessRequirements: {}, baseRollable: true, weaponRequirements: { family: 'dial', minimum: 1, maximum: 2 }, tags: ['foundation', 'dial', 'sky-island'] },
    { id: 'combat-technology', name: 'Combat Technology', type: 'brawl', power: 48, desc: 'A practical foundation for using mechanical equipment and specialized tools.', source: 'expanded', progressionType: 'foundation', parentIds: [], accessRequirements: {}, baseRollable: true, weaponRequirements: { family: 'technology', minimum: 1, maximum: 1 }, tags: ['foundation', 'technology'] },

    { id: 'one-sword-style', name: 'One Sword Style', type: 'sword', power: 70, desc: 'A formal single-blade discipline built on balanced, versatile swordsmanship.', source: 'canon', progressionType: 'discipline', parentIds: ['swordsmanship'], accessRequirements: { minimumBattleIQ: 45, minimumWeaponMastery: 45, allowedMentorTags: ['sword'] }, baseRollable: false, weaponRequirements: { family: 'blade', minimum: 1, maximum: 1 }, tags: ['discipline', 'blade'] },
    { id: 'two-sword-style', name: 'Two Sword Style', type: 'sword', power: 76, desc: 'A dual-blade discipline focused on speed, pressure, and coordination.', source: 'canon', progressionType: 'discipline', parentIds: ['swordsmanship'], accessRequirements: { minimumBattleIQ: 52, minimumSpeed: 55, minimumWeaponMastery: 55, allowedMentorTags: ['sword'] }, baseRollable: false, weaponRequirements: { family: 'blade', minimum: 2, maximum: 2 }, tags: ['discipline', 'blade', 'dual-wield'] },
    { id: 'three-sword-style', name: 'Three Sword Style', type: 'sword', power: 85, desc: 'A rare three-katana discipline demanding exceptional coordination and jaw strength.', source: 'canon', progressionType: 'discipline', parentIds: ['swordsmanship'], accessRequirements: { trainingResultId: 'three-sword-training' }, baseRollable: false, weaponRequirements: { family: 'blade', subtype: 'katana', minimum: 3, maximum: 3, specialUnlock: 'three-sword-training' }, tags: ['discipline', 'blade', 'santoryu'] },
    { id: 'gun-kata', name: 'Gun Kata', type: 'shoot', power: 65, desc: 'Close-quarters gunplay combining firearms with martial movement.', source: 'expanded', progressionType: 'discipline', parentIds: ['marksmanship'], accessRequirements: { minimumBattleIQ: 60, minimumSpeed: 55, minimumWeaponMastery: 60, allowedMentorTags: ['shoot', 'government', 'assassin'], rareIndependentChance: 0.02 }, baseRollable: false, weaponRequirements: { family: 'firearm', minimum: 1, maximum: 2 }, tags: ['discipline', 'firearm'] },
    { id: 'rokushiki', name: 'Rokushiki', type: 'martial', power: 80, desc: 'The Six Powers martial art practiced by Government agents and specialists.', source: 'canon', progressionType: 'discipline', parentIds: ['basic-martial-arts'], accessRequirements: { minimumBattleIQ: 58, minimumSpeed: 58, minimumWillpower: 55, allowedMentorTags: ['martial', 'government', 'assassin'], rareIndependentChance: 0.01 }, baseRollable: false, weaponRequirements: null, tags: ['discipline', 'martial', 'government'] },
    { id: 'life-return', name: 'Life Return', type: 'martial', power: 68, desc: 'An advanced body-control technique associated with Rokushiki training.', source: 'canon', progressionType: 'technique', parentIds: ['rokushiki'], accessRequirements: { minimumDisciplineMastery: 75, minimumWillpower: 65, minimumBodyControl: 75 }, baseRollable: false, weaponRequirements: null, tags: ['technique', 'martial', 'rokushiki'] },
    { id: 'soru', name: 'Soru', type: 'martial', power: 0, desc: 'A Rokushiki movement technique that uses explosive footwork.', source: 'canon', progressionType: 'technique', parentIds: ['rokushiki'], accessRequirements: { minimumDisciplineMastery: 55, minimumSpeed: 60 }, baseRollable: false, weaponRequirements: null, tags: ['technique', 'rokushiki'] },
    { id: 'geppo', name: 'Geppo', type: 'martial', power: 0, desc: 'A Rokushiki movement technique that lets the user kick the air.', source: 'canon', progressionType: 'technique', parentIds: ['rokushiki'], accessRequirements: { minimumDisciplineMastery: 62, minimumSpeed: 62, minimumStamina: 55 }, baseRollable: false, weaponRequirements: null, tags: ['technique', 'rokushiki'] },
    { id: 'tekkai', name: 'Tekkai', type: 'martial', power: 0, desc: 'A Rokushiki defensive technique that hardens the body through control.', source: 'canon', progressionType: 'technique', parentIds: ['rokushiki'], accessRequirements: { minimumDisciplineMastery: 60, minimumStrength: 55, minimumBodyControl: 60 }, baseRollable: false, weaponRequirements: null, tags: ['technique', 'rokushiki'] },
    { id: 'shigan', name: 'Shigan', type: 'martial', power: 0, desc: 'A Rokushiki finger-strike technique.', source: 'canon', progressionType: 'technique', parentIds: ['rokushiki'], accessRequirements: { minimumDisciplineMastery: 60, minimumSpeed: 55 }, baseRollable: false, weaponRequirements: null, tags: ['technique', 'rokushiki'] },
    { id: 'rankyaku', name: 'Rankyaku', type: 'martial', power: 0, desc: 'A Rokushiki kicking technique that sends a cutting air blade.', source: 'canon', progressionType: 'technique', parentIds: ['rokushiki'], accessRequirements: { minimumDisciplineMastery: 65, minimumSpeed: 58, minimumStrength: 52 }, baseRollable: false, weaponRequirements: null, tags: ['technique', 'rokushiki'] },
    { id: 'rokuogan', name: 'Rokuogan', type: 'martial', power: 0, desc: 'A rare Rokushiki shockwave technique requiring exceptional body control.', source: 'canon', progressionType: 'technique', parentIds: ['rokushiki'], accessRequirements: { minimumDisciplineMastery: 82, minimumStrength: 68, minimumWillpower: 65, minimumBodyControl: 75 }, baseRollable: false, weaponRequirements: null, tags: ['technique', 'rokushiki'] },
    { id: 'kami-e', name: 'Kami-e', type: 'martial', power: 0, desc: 'A Rokushiki evasion technique that lets the body move fluidly around attacks.', source: 'canon', progressionType: 'technique', parentIds: ['rokushiki'], accessRequirements: { minimumDisciplineMastery: 60, minimumSpeed: 60, minimumBodyControl: 65 }, baseRollable: false, weaponRequirements: null, tags: ['technique', 'rokushiki'] },
    { id: 'kanabo-style', name: 'Kanabo Style', type: 'brawl', power: 70, desc: 'Heavy club fighting focused on overwhelming force.', source: 'expanded', progressionType: 'discipline', parentIds: ['heavy-weapon-fighting'], accessRequirements: { minimumStrength: 68, minimumStamina: 60, allowedMentorTags: ['brawl'], rareIndependentChance: 0.015 }, baseRollable: false, weaponRequirements: { family: 'club', subtype: 'kanabo', minimum: 1, maximum: 1 }, tags: ['discipline', 'club'] },
    { id: 'dial-combat', name: 'Dial Combat', type: 'brawl', power: 66, desc: 'Sky Island fighting using impact, heat, and other Dials.', source: 'canon', progressionType: 'discipline', parentIds: ['sky-combat'], accessRequirements: { allowedRaces: ['Skypiean', 'Sky Islander', 'Birkan'] }, baseRollable: false, weaponRequirements: { family: 'dial', minimum: 1, maximum: 2 }, tags: ['discipline', 'dial'] },
    { id: 'fishman-karate', name: 'Fishman Karate', type: 'martial', power: 78, desc: 'A Fish-Man martial art that manipulates water in the environment and body.', source: 'canon', progressionType: 'discipline', parentIds: ['basic-martial-arts'], accessRequirements: { allowedRaces: ['Fishman'] }, baseRollable: false, weaponRequirements: null, tags: ['discipline', 'martial', 'fishman'] },
    { id: 'electro', name: 'Electro', type: 'martial', power: 72, desc: 'A Mink combat art that channels bioelectricity through strikes.', source: 'canon', progressionType: 'discipline', parentIds: ['basic-martial-arts'], accessRequirements: { allowedRaces: ['Mink'] }, baseRollable: false, weaponRequirements: null, tags: ['discipline', 'martial', 'mink'] },
    { id: 'cyborg-tech', name: 'Cyborg Tech', type: 'brawl', power: 70, desc: 'Integrated weapons and mechanical enhancements drive each attack.', source: 'canon', progressionType: 'discipline', parentIds: ['combat-technology'], accessRequirements: { allowedRaces: ['Cyborg'] }, baseRollable: false, weaponRequirements: { family: 'technology', minimum: 1, maximum: 1 }, tags: ['discipline', 'technology', 'cyborg'] },
    { id: 'black-leg-style', name: 'Black Leg Style', type: 'martial', power: 82, desc: 'A kick-focused martial art that deliberately keeps the hands free.', source: 'canon', progressionType: 'discipline', parentIds: ['basic-martial-arts'], accessRequirements: { minimumSpeed: 60, minimumStamina: 58, allowedMentorTags: ['martial'] }, baseRollable: false, weaponRequirements: null, tags: ['discipline', 'martial'] },
    { id: 'ryusoken', name: 'Ryusoken', type: 'martial', power: 78, desc: 'A Dragon Claw martial art using sweeping, momentum-driven strikes.', source: 'canon', progressionType: 'discipline', parentIds: ['basic-martial-arts'], accessRequirements: { minimumStrength: 60, minimumBattleIQ: 55, allowedMentorTags: ['martial'] }, baseRollable: false, weaponRequirements: null, tags: ['discipline', 'martial'] },
    { id: 'hasshoken', name: 'Hasshoken', type: 'martial', power: 74, desc: 'A vibration-based martial art that transmits force through the body.', source: 'canon', progressionType: 'discipline', parentIds: ['basic-martial-arts'], accessRequirements: { minimumStrength: 58, minimumWillpower: 55, allowedMentorTags: ['martial'] }, baseRollable: false, weaponRequirements: null, tags: ['discipline', 'martial'] },
    { id: 'okama-kenpo', name: 'Okama Kenpo', type: 'martial', power: 70, desc: 'A graceful, powerful martial art associated with the Okama.', source: 'canon', progressionType: 'discipline', parentIds: ['basic-martial-arts'], accessRequirements: { minimumSpeed: 52, allowedMentorTags: ['martial'] }, baseRollable: false, weaponRequirements: null, tags: ['discipline', 'martial'] },
    { id: 'newkama-kenpo', name: 'Newkama Kenpo', type: 'martial', power: 72, desc: 'A powerful variant of Okama Kenpo.', source: 'canon', progressionType: 'discipline', parentIds: ['basic-martial-arts'], accessRequirements: { minimumSpeed: 55, minimumWillpower: 55, allowedMentorTags: ['martial'] }, baseRollable: false, weaponRequirements: null, tags: ['discipline', 'martial'] },
    { id: 'demon-aura-style', name: 'Demon Aura Style', type: 'sword', power: 80, desc: 'An existing expanded aggressive sword discipline.', source: 'expanded', progressionType: 'discipline', parentIds: ['swordsmanship'], accessRequirements: { minimumWillpower: 70, minimumBattleIQ: 60, allowedMentorTags: ['sword'], rareIndependentChance: 0.005 }, baseRollable: false, weaponRequirements: { family: 'blade', minimum: 1, maximum: 1 }, tags: ['discipline', 'blade', 'expanded'] },
    { id: 'fishman-jujutsu', name: 'Fish-Man Jujutsu', type: 'martial', power: 74, desc: 'A Fish-Man water-based grappling discipline that redirects surrounding water and body fluids.', source: 'canon', progressionType: 'discipline', parentIds: ['basic-martial-arts'], accessRequirements: { minimumStrength: 58, minimumBattleIQ: 50, allowedRaces: ['Fishman'] }, baseRollable: false, weaponRequirements: null, tags: ['discipline', 'martial', 'fishman', 'grappling'] },
    { id: 'diable-jambe', name: 'Diable Jambe', type: 'martial', power: 0, desc: 'An advanced Black Leg technique that superheats the user’s leg for powerful kicks.', source: 'canon', progressionType: 'technique', parentIds: ['black-leg-style'], accessRequirements: { minimumDisciplineMastery: 72, minimumSpeed: 65, minimumStamina: 62, minimumWillpower: 60 }, baseRollable: false, weaponRequirements: null, tags: ['technique', 'martial', 'black-leg'] },
    { id: 'asura-nine-sword', name: 'Nine Sword Style: Asura', type: 'sword', power: 0, desc: 'A temporary three-sword manifestation, not an ordinary combat discipline.', source: 'canon', progressionType: 'advanced-state', parentIds: ['three-sword-style'], accessRequirements: { minimumWillpower: 88, minimumArmament: 72, minimumBattleIQ: 65 }, baseRollable: false, weaponRequirements: { family: 'blade', subtype: 'katana', minimum: 3, maximum: 3 }, tags: ['advanced-state', 'santoryu'] }
  ];
  V4.database.styles = styles;
}(window.OnePieceRollV4));


