/* Authoritative external weapon database. Add content here, never in the HTML. */
(function (V4) {
  'use strict';
  const rawWeapons = [
  // Supreme Grade
  { name: "Yoru", grade: "Supreme", type: "sword", power: 100, desc: "Mihawk's black blade. The strongest sword in the world.", advantages: ["Unmatched cutting power","Permanent black blade — indestructible","Immense range for a sword"], disadvantages: ["Enormous size requires great strength","Draws extreme attention","No forgiveness for unskilled users"], history: "Wielded by Dracule Mihawk, the World's Strongest Swordsman." },
  { name: "Ace", grade: "Supreme", type: "sword", power: 98, desc: "Whitebeard's personal naginata. A weapon of pure destruction.", advantages: ["Massive reach and power","Synergizes perfectly with Tremor-Tremor fruit","Intimidating presence"], disadvantages: ["Extremely heavy","Requires giant-level strength","Slow recovery after heavy swings"], history: "The signature weapon of Edward Newgate." },
  { name: "Murakumogiri", grade: "Supreme", type: "sword", power: 97, desc: "Whitebeard's bisento — one of the 12 Supreme Grade blades.", advantages: ["Incredible cutting and thrusting power","Long reach","Can be coated in Haki to devastating effect"], disadvantages: ["Very heavy","Requires high mastery","Rare and famous"], history: "One of the 12 Supreme Grade Meito, used by Whitebeard." },
  { name: "Shodai Kitetsu", grade: "Supreme", type: "sword", power: 96, desc: "The original Kitetsu. A cursed blade of supreme quality.", advantages: ["Extremely sharp","Cursed nature unsettles foes","Can become a black blade"], disadvantages: ["Dangerous to the wielder","Temperamental","Difficult to control"], history: "The first of the legendary Kitetsu blades." },
  { name: "Yoru (Replica)", grade: "Supreme", type: "sword", power: 92, desc: "A near-perfect replica of Mihawk's blade.", advantages: ["Near-Supreme cutting power","Excellent balance for its size"], disadvantages: ["Still requires immense strength","Not the true Yoru"], history: "Created by a master smith attempting to copy the black blade." },

  // Great Grade
  { name: "Wado Ichimonji", grade: "Great", type: "sword", power: 78, desc: "One of the 21 Great Grade swords — Zoro's most treasured blade.", advantages: ["Excellent balance and durability","Light enough for swift techniques","Can be turned into a black blade"], disadvantages: ["Requires skilled swordsmanship","Below Supreme grade cutting power","Emotionally irreplaceable"], history: "Originally owned by Kuina, passed to Roronoa Zoro." },
  { name: "Sandai Kitetsu", grade: "Great", type: "sword", power: 76, desc: "Cursed blade of the Kitetsu line. Extremely sharp and bloodthirsty.", advantages: ["Exceptional cutting ability","Cursed aura can intimidate","Responds well to strong will"], disadvantages: ["Cursed — can bring misfortune","Difficult to fully control","Attracts trouble"], history: "Third-generation Kitetsu, currently used by Roronoa Zoro." },
  { name: "Enma", grade: "Great", type: "sword", power: 88, desc: "Oden's legendary sword. Drains the user's Haki if not controlled.", advantages: ["Extremely high cutting power","Can force out latent Haki","Capable of permanent black-blade transformation"], disadvantages: ["Drains Armament Haki dangerously","Very hard to master","Punishes weak users"], history: "One of Kozuki Oden's twin swords, later given to Zoro." },
  { name: "Ame no Habakiri", grade: "Great", type: "sword", power: 87, desc: "Oden's other legendary sword. Said to cut the heavens.", advantages: ["Immense cutting power","Excellent for two-sword style","High compatibility with strong Haki users"], disadvantages: ["Requires great skill","Heavy for prolonged combat","Extremely rare"], history: "The paired sword of Enma, wielded by Kozuki Oden." },
  { name: "Kikoku", grade: "Great", type: "sword", power: 75, desc: "Trafalgar Law's cursed nodachi — an unusually long blade.", advantages: ["Extended reach complements Room ability","Cursed aura unsettles opponents","Excellent for thrusting and sweeping"], disadvantages: ["Unwieldy in close quarters","Cursed blades are temperamental","Very heavy for its length"], history: "A cursed blade carried by Trafalgar D. Water Law." },
  { name: "Shusui", grade: "Great", type: "sword", power: 80, desc: "A national treasure of Wano. Black blade of Ryuma.", advantages: ["Already a permanent black blade","Exceptional durability","High prestige"], disadvantages: ["Extremely famous — draws attention","Heavy responsibility to wield","Hard to replace"], history: "The black blade of the legendary samurai Ryuma." },
  { name: "Nidai Kitetsu", grade: "Great", type: "sword", power: 82, desc: "Second-generation Kitetsu. Dangerous and extremely sharp.", advantages: ["Superior cutting power","Strong cursed presence","Responds to strong will"], disadvantages: ["Highly cursed","Difficult to control","Can harm the user"], history: "The second of the Kitetsu line, once held in Wano." },
  { name: "Durandal", grade: "Great", type: "sword", power: 74, desc: "Cavendish's beautiful and deadly sword.", advantages: ["Excellent balance","Elegant yet lethal","High compatibility with speed-based styles"], disadvantages: ["Not the strongest in raw power","Requires refined technique"], history: "The beloved blade of Cavendish, the White Knight." },
  { name: "Hassaikai", grade: "Great", type: "brawl", power: 75, desc: "Kaido's spiked kanabo — a weapon of pure devastation.", advantages: ["Massive blunt force damage","Synergizes with Haki coating","Intimidates on sight"], disadvantages: ["Extremely heavy — needs immense strength","Slow wind-up","Useless at range"], history: "The signature weapon of Kaido, King of the Beasts." },
  { name: "Napoleon", grade: "Great", type: "sword", power: 72, desc: "Big Mom's living hat that transforms into a sword.", advantages: ["Can change form","Surprisingly durable","Linked to its owner"], disadvantages: ["Requires Homies connection","Less effective without Big Mom's power"], history: "One of Charlotte Linlin's special Homies." },
  { name: "Sokotsu", grade: "Great", type: "sword", power: 73, desc: "A heavy Wano-style blade favored by strong swordsmen.", advantages: ["High durability","Excellent for heavy strikes","Good Haki conductivity"], disadvantages: ["Slower than lighter blades","Requires significant strength"], history: "A respected blade from Wano's blacksmithing tradition." },

  // Skillful Grade
  { name: "Yubashiri", grade: "Skillful", type: "sword", power: 58, desc: "An elegant Skillful Grade sword, once used by Zoro.", advantages: ["Light and fast","Excellent for precision","Beautiful craftsmanship"], disadvantages: ["Lower durability than Great Grade","Destroyed by rust in the past"], history: "One of Zoro's former swords, lost to corrosion." },
  { name: "Kashu", grade: "Skillful", type: "sword", power: 55, desc: "A cursed Skillful Grade sword with a bloodthirsty nature.", advantages: ["Sharp and aggressive","Cursed presence can unnerve foes"], disadvantages: ["Cursed — may influence the user","Not as refined as higher grades"], history: "A cursed blade once wielded by Zoro." },
  { name: "Shigure", grade: "Skillful", type: "sword", power: 52, desc: "Tashigi's trusted sword.", advantages: ["Reliable and well-balanced","Good for disciplined swordsmanship"], disadvantages: ["Average power","No special properties"], history: "The sword of Marine Captain Tashigi." },
  { name: "Kiribachi", grade: "Skillful", type: "sword", power: 60, desc: "Arlong's massive saw-tooth sword.", advantages: ["Brutal cutting and tearing power","Intimidating design","Strong against flesh and wood"], disadvantages: ["Heavy and clumsy","Poor against metal or Haki"], history: "The signature weapon of Arlong." },
  { name: "Otose's Cane", grade: "Skillful", type: "brawl", power: 45, desc: "A reinforced cane that doubles as a weapon.", advantages: ["Disguised as a walking stick","Surprisingly sturdy"], disadvantages: ["Limited reach","Low raw power"], history: "Used by the old woman Otose of the Yellow City." },
  { name: "Jitte", grade: "Skillful", type: "brawl", power: 50, desc: "Smoker's seastone-tipped jitte.", advantages: ["Can nullify Devil Fruit powers on contact","Good for catching blades"], disadvantages: ["Short range","Requires precise timing"], history: "The signature weapon of Smoker the White Hunter." },
  { name: "Reject Dial", grade: "Skillful", type: "brawl", power: 68, desc: "A Sky Island weapon that stores and releases massive impact.", advantages: ["Devastating counter damage","Can one-shot weaker opponents"], disadvantages: ["Damages the user as well","Limited charges","Requires precise timing"], history: "A rare and dangerous Dial used by Shandian warriors." },
  { name: "Eisen Dial Shield", grade: "Skillful", type: "brawl", power: 48, desc: "A shield formed from iron clouds.", advantages: ["Strong defensive capability","Can be reshaped"], disadvantages: ["Mostly defensive","Limited offensive use"], history: "Used by Ohm of the Skypiea priests." },

  // Standard Grade
  { name: "Basic Cutlass", grade: "Standard", type: "sword", power: 20, desc: "Standard pirate cutlass.", advantages: ["Cheap and replaceable","Easy to learn","Good for shipboard combat"], disadvantages: ["Breaks easily against graded weapons","Low cutting power","No special properties"], history: "The most common weapon on the seas." },
  { name: "Flintlock Pistol", grade: "Standard", type: "shoot", power: 25, desc: "A reliable sidearm common across the Grand Line.", advantages: ["Ranged attack capability","Easy to conceal","No stamina cost to use"], disadvantages: ["Low damage against strong opponents","Limited ammunition","Ineffective against Haki or Logia users"], history: "Standard issue for Marines and pirates alike." },
  { name: "Den Den Mushi Rifle", grade: "Standard", type: "shoot", power: 35, desc: "A long-range rifle used by Marines and bounty hunters.", advantages: ["Good accuracy at range","Higher power than a pistol"], disadvantages: ["Slow reload","Cumbersome in close combat"], history: "Common among Marine snipers and island defenders." },
  { name: "Bo Staff", grade: "Standard", type: "brawl", power: 28, desc: "A simple wooden staff.", advantages: ["Long reach for a basic weapon","Easy to use","Non-lethal options"], disadvantages: ["Low damage","Breaks against strong opponents"], history: "A basic training and self-defense weapon." },
  { name: "Claw Gauntlets", grade: "Standard", type: "brawl", power: 32, desc: "Metal claws worn over the hands.", advantages: ["Enhances bare-handed strikes","Good for climbing and grappling"], disadvantages: ["Short range","Limited against armored foes"], history: "Favored by assassins and beast-like fighters." },
  { name: "Tonfa", grade: "Standard", type: "brawl", power: 30, desc: "Pair of side-handled batons.", advantages: ["Excellent for blocking","Fast strikes","Good for martial artists"], disadvantages: ["Requires training","Low raw power"], history: "Used by various martial artists across the seas." },
  { name: "Kusarigama", grade: "Skillful", type: "sword", power: 54, desc: "A chain-sickle weapon combining reach and unpredictability.", advantages: ["Versatile range","Can bind opponents","Hard to predict"], disadvantages: ["Difficult to master","Risk of self-injury"], history: "A traditional weapon sometimes seen in Wano and the East Blue." },
  { name: "Greatsword", grade: "Skillful", type: "sword", power: 62, desc: "A massive two-handed sword.", advantages: ["High raw power","Wide sweeping attacks"], disadvantages: ["Very slow","Requires high strength"], history: "Favored by power-focused swordsmen." },
  { name: "Dual Daggers", grade: "Standard", type: "sword", power: 28, desc: "A pair of short blades for close combat.", advantages: ["Fast and concealable","Good for dual-wielding styles"], disadvantages: ["Very short reach","Low power against tough opponents"], history: "Common among thieves and assassins." },
  { name: "Sniper Rifle", grade: "Skillful", type: "shoot", power: 58, desc: "A high-precision long-range rifle.", advantages: ["Excellent accuracy","High damage at long range"], disadvantages: ["Useless in close combat","Requires setup time"], history: "Used by elite marksmen like Yasopp and Usopp." },
  { name: "Cannon", grade: "Great", type: "shoot", power: 70, desc: "A portable (or ship-mounted) heavy cannon.", advantages: ["Massive explosive power","Area damage"], disadvantages: ["Extremely slow","Heavy and impractical for single combat"], history: "Common on pirate ships and Marine vessels." }
,
  { name: 'Training Katana', grade: 'Standard', type: 'sword', power: 28, desc: 'A practical katana used for disciplined sword training.', source: 'canon', family: 'blade', subtype: 'katana', tags: ['sword', 'katana'], unique: false, named: false, rarityClass: 'generic', acquisitionWeight: 12 },
  { name: 'Sea-forged Katana', grade: 'Skillful', type: 'sword', power: 52, desc: 'A durable, well-balanced katana from a reputable smith.', source: 'expanded', family: 'blade', subtype: 'katana', tags: ['sword', 'katana'], unique: false, named: false, rarityClass: 'generic', acquisitionWeight: 8 },
  { name: 'Wano Steel Katana', grade: 'Great', type: 'sword', power: 68, desc: 'A finely forged katana suited to a proven swordsman.', source: 'expanded', family: 'blade', subtype: 'katana', tags: ['sword', 'katana'], unique: false, named: false, rarityClass: 'generic', acquisitionWeight: 4 },
  { name: 'Standard Kanabo', grade: 'Standard', type: 'brawl', power: 35, desc: 'A common iron-studded club.', source: 'canon', family: 'club', subtype: 'kanabo', tags: ['club', 'kanabo'], unique: false, named: false, rarityClass: 'generic', acquisitionWeight: 10 },
  { name: 'Heavy Iron Kanabo', grade: 'Skillful', type: 'brawl', power: 52, desc: 'A heavy military kanabo for trained fighters.', source: 'expanded', family: 'club', subtype: 'kanabo', tags: ['club', 'kanabo', 'heavy'], unique: false, named: false, rarityClass: 'generic', acquisitionWeight: 7 },
  { name: 'Spiked Kanabo', grade: 'Great', type: 'brawl', power: 66, desc: 'A brutal reinforced kanabo suited to powerful combatants.', source: 'expanded', family: 'club', subtype: 'kanabo', tags: ['club', 'kanabo', 'heavy'], unique: false, named: false, rarityClass: 'generic', acquisitionWeight: 4 },
  { name: 'Boarding Axe', grade: 'Standard', type: 'brawl', power: 32, desc: 'A practical axe for shipboard fighting.', source: 'canon', family: 'axe', subtype: 'boarding-axe', tags: ['axe', 'one-handed'], unique: false, named: false, rarityClass: 'generic', acquisitionWeight: 8 },
  { name: 'Combat Dagger', grade: 'Standard', type: 'sword', power: 24, desc: 'A durable close-quarters blade.', source: 'canon', family: 'dagger', subtype: 'combat-dagger', tags: ['dagger', 'blade'], unique: false, named: false, rarityClass: 'generic', acquisitionWeight: 9 },
  { name: 'Marine Spear', grade: 'Standard', type: 'brawl', power: 34, desc: 'A straightforward spear with reliable reach.', source: 'canon', family: 'polearm', subtype: 'spear', tags: ['polearm', 'spear'], unique: false, named: false, rarityClass: 'generic', acquisitionWeight: 8 },
  { name: 'Weather Baton', grade: 'Standard', type: 'brawl', power: 30, desc: 'A simple weather-reading and defensive tool.', source: 'canon', family: 'weather-tool', subtype: 'baton', tags: ['weather-tool', 'navigation'], unique: false, named: false, rarityClass: 'generic', acquisitionWeight: 6 },
  { name: 'Combat Clima-Tact', grade: 'Skillful', type: 'brawl', power: 54, desc: 'A weather tool adapted for combat use.', source: 'canon', family: 'weather-tool', subtype: 'clima-tact', tags: ['weather-tool', 'technology'], unique: false, named: false, rarityClass: 'generic', acquisitionWeight: 3 },
  { name: 'Mechanical Arm', grade: 'Skillful', type: 'brawl', power: 55, desc: 'A reinforced mechanical arm with built-in tools.', source: 'expanded', family: 'technology', subtype: 'mechanical-arm', tags: ['technology', 'cybernetic'], unique: false, named: false, rarityClass: 'generic', acquisitionWeight: 4 },
  { name: 'Impact Dial', grade: 'Standard', type: 'brawl', power: 38, desc: 'A common combat Dial that stores and releases force.', source: 'canon', family: 'dial', subtype: 'impact', tags: ['dial', 'stored-force'], unique: false, named: false, rarityClass: 'generic', acquisitionWeight: 8 },
  // Foundation batch 01: ordinary equipment, deliberately distinct from named canon relics.
  { id: 'deck-saber', name: 'Deck Saber', grade: 'Standard', type: 'sword', power: 26, desc: 'A practical single-edged saber issued by a shipboard armory.', source: 'expanded', family: 'blade', subtype: 'saber', tags: ['blade', 'saber', 'one-handed'], quality: 'Standard', handlingDifficulty: 30, unique: false, named: false, rarityClass: 'generic', acquisitionWeight: 12 },
  { id: 'iron-cutlass', name: 'Iron Cutlass', grade: 'Standard', type: 'sword', power: 30, desc: 'A heavier common cutlass built to survive repeated shipboard clashes.', source: 'expanded', family: 'blade', subtype: 'cutlass', tags: ['blade', 'cutlass', 'one-handed'], quality: 'Standard', handlingDifficulty: 34, unique: false, named: false, rarityClass: 'generic', acquisitionWeight: 10 },
  { id: 'practice-nodachi', name: 'Practice Nodachi', grade: 'Skillful', type: 'sword', power: 48, desc: 'A long training blade for learning reach, posture, and two-handed control.', source: 'expanded', family: 'blade', subtype: 'nodachi', tags: ['blade', 'two-handed', 'training'], quality: 'Skillful', handlingDifficulty: 54, unique: false, named: false, rarityClass: 'generic', acquisitionWeight: 7 },
  { id: 'wooden-club', name: 'Wooden Club', grade: 'Standard', type: 'brawl', power: 24, desc: 'A simple hardwood club common among dockworkers and inexperienced pirates.', source: 'expanded', family: 'club', subtype: 'wooden-club', tags: ['club', 'one-handed'], quality: 'Standard', handlingDifficulty: 22, unique: false, named: false, rarityClass: 'generic', acquisitionWeight: 12 },
  { id: 'iron-mace', name: 'Iron Mace', grade: 'Standard', type: 'brawl', power: 34, desc: 'A compact iron-headed mace intended for direct, armor-crushing strikes.', source: 'expanded', family: 'club', subtype: 'mace', tags: ['club', 'mace', 'one-handed'], quality: 'Standard', handlingDifficulty: 42, unique: false, named: false, rarityClass: 'generic', acquisitionWeight: 9 },
  { id: 'sailor-war-hammer', name: 'Sailor War Hammer', grade: 'Skillful', type: 'brawl', power: 50, desc: 'A reinforced hammer carried by strong boarding parties.', source: 'expanded', family: 'club', subtype: 'war-hammer', tags: ['club', 'hammer', 'heavy'], quality: 'Skillful', handlingDifficulty: 58, unique: false, named: false, rarityClass: 'generic', acquisitionWeight: 6 },
  { id: 'matchlock-musket', name: 'Matchlock Musket', grade: 'Standard', type: 'shoot', power: 30, desc: 'A long, slow-loading firearm used for basic ranged defense.', source: 'expanded', family: 'firearm', subtype: 'musket', tags: ['firearm', 'longarm', 'black-powder'], quality: 'Standard', handlingDifficulty: 38, unique: false, named: false, rarityClass: 'generic', acquisitionWeight: 11 },
  { id: 'marine-carbine', name: 'Marine Carbine', grade: 'Skillful', type: 'shoot', power: 44, desc: 'A compact service rifle suited to patrols and close shipboard fire.', source: 'expanded', family: 'firearm', subtype: 'carbine', tags: ['firearm', 'longarm', 'service'], quality: 'Skillful', handlingDifficulty: 47, unique: false, named: false, rarityClass: 'generic', acquisitionWeight: 7 },
  { id: 'twin-flintlock-pistols', name: 'Twin Flintlock Pistols', grade: 'Skillful', type: 'shoot', power: 42, desc: 'A matched pair of short-range pistols for a mobile gunfighter.', source: 'expanded', family: 'firearm', subtype: 'pistol', tags: ['firearm', 'pistol', 'dual-wield'], quality: 'Skillful', handlingDifficulty: 52, unique: false, named: false, rarityClass: 'generic', acquisitionWeight: 6 },
  { id: 'wooden-spear', name: 'Wooden Spear', grade: 'Standard', type: 'brawl', power: 28, desc: 'An affordable spear that teaches spacing and thrust timing.', source: 'expanded', family: 'polearm', subtype: 'spear', tags: ['polearm', 'spear', 'training'], quality: 'Standard', handlingDifficulty: 33, unique: false, named: false, rarityClass: 'generic', acquisitionWeight: 11 },
  { id: 'sailor-glaive', name: 'Sailor Glaive', grade: 'Skillful', type: 'brawl', power: 48, desc: 'A hooked polearm built for reach and controlling a boarding lane.', source: 'expanded', family: 'polearm', subtype: 'glaive', tags: ['polearm', 'glaive', 'reach'], quality: 'Skillful', handlingDifficulty: 57, unique: false, named: false, rarityClass: 'generic', acquisitionWeight: 6 },
  { id: 'training-naginata', name: 'Training Naginata', grade: 'Skillful', type: 'brawl', power: 46, desc: 'A balanced polearm for formal two-handed drilling and wide sweeps.', source: 'expanded', family: 'polearm', subtype: 'naginata', tags: ['polearm', 'naginata', 'training'], quality: 'Skillful', handlingDifficulty: 55, unique: false, named: false, rarityClass: 'generic', acquisitionWeight: 6 },
  { id: 'quarterstaff', name: 'Quarterstaff', grade: 'Standard', type: 'brawl', power: 26, desc: 'A sturdy staff useful for defense, reach, and nonlethal fighting.', source: 'expanded', family: 'staff', subtype: 'quarterstaff', tags: ['staff', 'two-handed', 'training'], quality: 'Standard', handlingDifficulty: 28, unique: false, named: false, rarityClass: 'generic', acquisitionWeight: 11 },
  { id: 'iron-staff', name: 'Iron Staff', grade: 'Skillful', type: 'brawl', power: 43, desc: 'A metal staff that trades speed for durability and impact.', source: 'expanded', family: 'staff', subtype: 'iron-staff', tags: ['staff', 'two-handed', 'durable'], quality: 'Skillful', handlingDifficulty: 46, unique: false, named: false, rarityClass: 'generic', acquisitionWeight: 7 },
  { id: 'hand-axe', name: 'Hand Axe', grade: 'Standard', type: 'brawl', power: 29, desc: 'A compact axe that can serve as a tool or emergency weapon.', source: 'expanded', family: 'axe', subtype: 'hand-axe', tags: ['axe', 'one-handed', 'tool'], quality: 'Standard', handlingDifficulty: 36, unique: false, named: false, rarityClass: 'generic', acquisitionWeight: 10 },
  { id: 'battle-axe', name: 'Battle Axe', grade: 'Skillful', type: 'brawl', power: 49, desc: 'A two-handed axe with broad, committed cutting arcs.', source: 'expanded', family: 'axe', subtype: 'battle-axe', tags: ['axe', 'two-handed', 'heavy'], quality: 'Skillful', handlingDifficulty: 59, unique: false, named: false, rarityClass: 'generic', acquisitionWeight: 6 },
  { id: 'fighting-knife', name: 'Fighting Knife', grade: 'Standard', type: 'sword', power: 22, desc: 'A plain close-quarters knife for sailors, scouts, and guards.', source: 'expanded', family: 'dagger', subtype: 'fighting-knife', tags: ['dagger', 'blade', 'concealable'], quality: 'Standard', handlingDifficulty: 25, unique: false, named: false, rarityClass: 'generic', acquisitionWeight: 12 },
  { id: 'twin-knives', name: 'Twin Knives', grade: 'Skillful', type: 'sword', power: 38, desc: 'A matched pair of short blades used for rapid close-range pressure.', source: 'expanded', family: 'dagger', subtype: 'twin-knives', tags: ['dagger', 'blade', 'dual-wield'], quality: 'Skillful', handlingDifficulty: 48, unique: false, named: false, rarityClass: 'generic', acquisitionWeight: 7 },
  { id: 'flash-dial', name: 'Flash Dial', grade: 'Standard', type: 'brawl', power: 20, desc: 'A common Sky Island Dial that releases a blinding burst of stored light.', source: 'canon', family: 'dial', subtype: 'flash', tags: ['dial', 'utility', 'sky-island'], quality: 'Standard', handlingDifficulty: 32, unique: false, named: false, rarityClass: 'generic', acquisitionWeight: 9 },
  { id: 'heat-dial', name: 'Heat Dial', grade: 'Standard', type: 'brawl', power: 32, desc: 'A common Sky Island Dial that stores and releases heat.', source: 'canon', family: 'dial', subtype: 'heat', tags: ['dial', 'utility', 'sky-island'], quality: 'Standard', handlingDifficulty: 40, unique: false, named: false, rarityClass: 'generic', acquisitionWeight: 8 },
  { id: 'navigator-weather-rod', name: 'Navigator Weather Rod', grade: 'Standard', type: 'brawl', power: 24, desc: 'A simple weather-reading rod adapted for defensive swings and signals.', source: 'expanded', family: 'weather-tool', subtype: 'weather-rod', tags: ['weather-tool', 'navigation', 'utility'], quality: 'Standard', handlingDifficulty: 30, unique: false, named: false, rarityClass: 'generic', acquisitionWeight: 9 },
  { id: 'compact-dial-launcher', name: 'Compact Dial Launcher', grade: 'Skillful', type: 'brawl', power: 45, desc: 'A small mechanical launcher built around replaceable Dials.', source: 'expanded', family: 'technology', subtype: 'dial-launcher', tags: ['technology', 'dial', 'ranged'], quality: 'Skillful', handlingDifficulty: 51, unique: false, named: false, rarityClass: 'generic', acquisitionWeight: 5 },
  { id: 'brass-knuckles', name: 'Brass Knuckles', grade: 'Standard', type: 'brawl', power: 25, desc: 'Simple metal knuckle guards for close-range punches and grappling.', source: 'expanded', family: 'martial-tool', subtype: 'knuckle-guard', tags: ['martial-tool', 'brawling', 'one-handed'], quality: 'Standard', handlingDifficulty: 24, unique: false, named: false, rarityClass: 'generic', acquisitionWeight: 11 },
  { id: 'weighted-chain', name: 'Weighted Chain', grade: 'Skillful', type: 'brawl', power: 40, desc: 'A flexible weighted chain requiring patience, spacing, and careful control.', source: 'expanded', family: 'martial-tool', subtype: 'weighted-chain', tags: ['martial-tool', 'flexible', 'reach'], quality: 'Skillful', handlingDifficulty: 60, unique: false, named: false, rarityClass: 'generic', acquisitionWeight: 5 }
];
  const slug = value => value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
  const familyFor = weapon => weapon.family || (weapon.type === 'sword' ? 'blade' : weapon.type === 'shoot' ? 'firearm' : weapon.name.includes('Dial') ? 'dial' : weapon.name.includes('Staff') ? 'staff' : 'martial-tool');
  V4.database.weapons = rawWeapons.map(weapon => ({
    ...weapon, id: weapon.id || slug(weapon.name), source: weapon.source || weapon.src || 'canon',
    family: familyFor(weapon), subtype: weapon.subtype || familyFor(weapon),
    tags: weapon.tags || [weapon.type, familyFor(weapon)].filter(Boolean), quality: weapon.quality || weapon.grade,
    handlingDifficulty: weapon.handlingDifficulty ?? Math.max(1, Math.min(100, Math.round(100 - weapon.power * 0.55))),
    unique: weapon.unique ?? false, acquisitionWeight: weapon.acquisitionWeight ?? 1
  }));
}(window.OnePieceRollV4));


