/* Display-only preferences. They never enter generation, saves, or combat math. */
(function(V4){
  'use strict'; const api=V4.ui.settings=V4.ui.settings||{}, key='op-v553-display-options', defaults={theme:'grand-line',density:'comfortable',motion:'full'};
  const load=()=>{try{return{...defaults,...JSON.parse(localStorage.getItem(key)||'{}')}}catch{return{...defaults}}};
  const apply=options=>{const next={...defaults,...options};document.body.dataset.theme=next.theme;document.body.dataset.density=next.density;document.body.dataset.motion=next.motion;localStorage.setItem(key,JSON.stringify(next));return next;};
  api.apply=apply; api.load=load;
  api.render=()=>{const host=document.getElementById('options-panel');if(!host||typeof host.querySelector!=='function')return;const current=load();host.innerHTML=`<h3>Display & Accessibility</h3><div class="sandbox-grid options-grid"><label><span>Theme</span><select id="option-theme"><option value="grand-line">Grand Line Night</option><option value="marine">Marine Intelligence</option><option value="sunny">Sunny Voyage</option><option value="void">Void Eclipse</option></select></label><label><span>Layout density</span><select id="option-density"><option value="comfortable">Comfortable</option><option value="compact">Compact</option></select></label><label><span>Motion</span><select id="option-motion"><option value="full">Full presentation</option><option value="reduced">Reduce nonessential motion</option></select></label></div><div class="pill-row"><button class="btn" type="button" id="save-options">Apply display options</button><button class="btn-small" type="button" id="reset-options">Reset</button></div><p class="stat-desc">Battle accessibility controls still apply to an individual match; these are global visual preferences.</p>`;
    host.querySelector('#option-theme').value=current.theme;host.querySelector('#option-density').value=current.density;host.querySelector('#option-motion').value=current.motion;
    host.querySelector('#save-options').onclick=()=>{apply({theme:host.querySelector('#option-theme').value,density:host.querySelector('#option-density').value,motion:host.querySelector('#option-motion').value});api.render();};host.querySelector('#reset-options').onclick=()=>{localStorage.removeItem(key);apply(defaults);api.render();};
  };apply(load());if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',api.render,{once:true});else api.render();
}(window.OnePieceRollV4));
